import {FIXTURES,TEAMS,TEAM} from './data.js';
import {uiState} from './state.js';
import {crest,leagueLogo,profileButton,formDots} from './helpers.js';
import {icon} from './icons.js';

const homeNews=(id,title)=>`<button class="v11-home-news" data-route="video"><div class="v11-photo-placeholder hero ${id}">${crest(id)}</div><span class="v11-round-play">${icon('play')}</span><b>${title}</b></button>`;

export function homeView(){return `<div class="v11-ref-pack v11-home">
<section class="v11-home-head"><div class="v11-home-brand">${leagueLogo()}<div><b>LIGA MUNICIPAL DE FÚTBOL</b><strong>JUVENTINO ROSAS</strong><span>GUANAJUATO</span></div></div><button class="v11-bell" data-route="notifications" aria-label="Notificaciones">${icon('bell')}</button></section>
<div class="v11-story-strip">${['america','huerta','promesas','galeana','lobos'].map(id=>`<button data-route="teams"><span>${crest(id)}</span><small>${TEAM(id).short}</small></button>`).join('')}</div>
<section class="v11-home-body">
<button class="v11-result-hero" data-route="competition"><div class="v11-photo-placeholder field"></div><div class="v11-scorebar">${crest('america')}<b>AMÉRICA</b><strong>2 - 1</strong><b>LA HUERTA</b>${crest('huerta')}<small>FINAL</small></div></button>
${homeNews('promesas','Delantero de Promesas brilla en la Jornada 6')}
<div class="v11-local-strip"><div><b>Nuestra liga, nuestra gente</b><small>Juventino Rosas, Guanajuato</small><em>LIGA LOCAL</em></div>${leagueLogo()}</div>
${homeNews('galeana','La revelación de Atl. Galeana en esta temporada')}
${homeNews('lobos','Un golazo de Lobos CDG que ya es viral')}
<div class="v11-section-title"><h2>Momentos</h2><button data-route="moments">Ver todo</button></div>
<div class="v11-moment-grid">${[['america','América 2-1 La Huerta','0:45'],['promesas','Promesas 3-0 San José','1:12'],['galeana','Atl. Galeana 1-1 Lobos','0:58'],['huerta','La Huerta 4-2 Cuervos','1:03']].map(([id,t,d])=>`<button data-route="moments"><div class="v11-photo-placeholder mini">${crest(id)}</div><span>${d}</span><b>${t}</b></button>`).join('')}</div>
<h2 class="v11-games-title">Únete a los juegos</h2>
<div class="v11-games-grid"><button data-route="predictor"><small>▥ Predicciones</small><div class="v11-game-art"><b>2</b><b>?</b></div><strong>Pronostica Seis</strong><span>Acierta en los resultados de la Liga Municipal</span><em>Juega a Pronostica Seis</em></button><button data-route="fantasy"><small>♟ Fantasy</small><div class="v11-shirt-art">👕</div><strong>Arma tu Equipo</strong><span>Fichajes, puntos y más de la liga local</span><em>Juega al Fantasy</em></button></div>
<button class="v11-week" data-route="scorers"><div><b>JUGADOR<br>DE LA SEMANA</b><strong>¿Quién es tu Jugador de la Semana?</strong></div><div class="v11-week-players">${['america','galeana','promesas','lobos'].map(id=>crest(id)).join('')}</div></button>
<div class="v11-news-grid">${[['america','América Veteranos sigue invicto en la Liga Municipal'],['promesas','Promesas FC se afianza en la parte alta de la tabla'],['galeana','Atl. Galeana sueña con el título']].map(([id,t])=>`<button data-route="video"><div class="v11-photo-placeholder news">${crest(id)}</div><b>${t}</b></button>`).join('')}</div>
</section></div>`}

const segments=()=>[['compact','Compacta'],['full','Completa'],['criteria','Criterios de desempate']].map(([v,l])=>`<button data-action="standings" data-value="${v}" class="${uiState.standingsMode===v?'active':''}">${l}</button>`).join('');
const phases=()=>[['playoff','Play-off'],['round16','Octavos de final'],['quarter','Cuartos de final'],['semi','Semifinales'],['final','Final']].map(([v,l])=>`<button data-action="phase" data-value="${v}" class="${uiState.bracketPhase===v?'active':''}">${l}</button>`).join('');

function fixturesView(){const items=FIXTURES[uiState.selectedDate]||FIXTURES['13 oct'];return `<div class="v11-fixtures"><div class="v11-date-strip">${Object.keys(FIXTURES).map(d=>`<button data-action="date" data-value="${d}" class="${uiState.selectedDate===d?'active':''}">${d==='10 sept'?'jue 10 sept':d==='13 oct'?'mar 13 oct':'mié 14 oct'}</button>`).join('')}</div><h2>${uiState.selectedDate==='13 oct'?'martes, 13 octubre 2026':uiState.selectedDate==='14 oct'?'miércoles, 14 octubre 2026':'jueves, 10 septiembre 2026'}</h2><section class="v11-fixture-card"><h3>Liga local - Jornada 2</h3>${items.map(([a,b,time])=>`<div class="v11-fixture-row"><div>${crest(a)}<b>${TEAM(a).name}</b>${crest(b)}<b>${TEAM(b).name}</b></div><span>${time}</span><button>Ver detalles</button></div>`).join('')}</section><div class="v11-league-banner">${leagueLogo()}<b>LIGA MUNICIPAL DE FÚTBOL<br>JUVENTINO ROSAS, GUANAJUATO</b><span>⚽</span></div></div>`}

function standingsView(){if(uiState.standingsMode==='criteria')return `<div class="v11-standings"><div class="v11-segments">${segments()}</div><section class="v11-criteria"><h2>Criterios de desempate</h2><p>1. Diferencia de goles.</p><p>2. Goles a favor.</p><p>3. Resultado entre los equipos empatados.</p><p>4. Criterios oficiales definidos por la Liga Municipal para la temporada.</p></section></div>`;const rows=TEAMS.slice(0,uiState.standingsMode==='full'?10:7);return `<div class="v11-standings"><div class="v11-segments">${segments()}</div><div class="v11-stand-head"><span></span><span></span><span></span><b>P</b><b>+/-</b><b>PTOS</b><b>FORMA</b></div><h3>DIRECTOS A OCTAVOS</h3><div class="v11-stand-rows">${rows.map((t,i)=>`<div class="v11-stand-row"><span>${i+1}</span>${crest(t.id)}<strong>${t.name}</strong><b>${t.p}</b><b>${t.gd}</b><b>${t.pts}</b>${formDots(t.form)}</div>`).join('')}</div></div>`}

function bracketView(){if(uiState.bracketPhase==='final')return `<div class="v11-bracket-view"><div class="v11-phase-strip">${phases()}</div><div class="v11-final-empty"><div class="v11-final-card">${crest('america')}<b>AME</b><strong>vs</strong>${crest('lobos')}<b>LOB</b></div><div class="v11-trophy-css">♕</div></div></div>`;const pairs=[['america','huerta'],['promesas','franco'],['galeana','lobos'],['juventino','pozos'],['cuenda','esperanza'],['lobos','promesas'],['franco','america'],['pozos','huerta']];return `<div class="v11-bracket-view"><div class="v11-phase-strip">${phases()}</div><div class="v11-bracket-scroll"><div class="v11-bracket-board">${pairs.map((p,i)=>`<div class="v11-bracket-match" style="top:${i*92}px"><div><span>${i+1}</span>${crest(p[0])}<b>${TEAM(p[0]).code}</b></div><div><span>${16-i}</span>${crest(p[1])}<b>${TEAM(p[1]).code}</b></div></div><div class="v11-bracket-next" style="top:${i*92+25}px;left:225px">Ganador del play-off</div>`).join('')}</div></div></div>`}

export function competitionView(){return `<div class="v11-ref-pack v11-competition"><section class="v11-comp-head"><h1>Competición</h1>${profileButton()}<div class="v11-neon-lines"></div></section><div class="v11-comp-tabs">${[['fixtures','Partidos y resultados'],['standings','Clasificación'],['bracket','Cuadro']].map(([id,label])=>`<button data-action="comp-tab" data-value="${id}" class="${uiState.competitionTab===id?'active':''}">${label}</button>`).join('')}</div>${uiState.competitionTab==='fixtures'?fixturesView():uiState.competitionTab==='standings'?standingsView():bracketView()}</div>`}

const videoRail=(title,headline,id)=>`<section class="v11-video-section"><h2>${title}</h2><div class="v11-video-rail"><button data-action="login"><div class="v11-video-thumb">${crest(id)}<strong>${headline}</strong><span class="v11-lock">▣</span></div><em>${icon('play')} Iniciar sesión para ver</em></button><button data-action="login"><div class="v11-video-thumb alt">${crest('promesas')}<strong>${headline}</strong></div><em>${icon('play')} Iniciar sesión para ver</em></button></div></section>`;
const miniVideo=(title,ids)=>`<section class="v11-video-section"><h2>${title}</h2><div class="v11-mini-video-grid">${ids.map(id=>`<button><div>${crest(id)}<span>${icon('play')}</span></div><b>${title==='Conferencias'?'Conferencia':'Entrevista'} post-partido<br>${TEAM(id).short}</b></button>`).join('')}</div></section>`;
export function videoView(){return `<div class="v11-ref-pack v11-video"><section class="v11-video-hero"><div class="v11-video-top"><div><b>LIGA JUVENTINO TV</b><span>FÚTBOL LOCAL, PASIÓN REAL</span></div>${profileButton()}</div><div class="v11-video-player-art"><div class="v11-player-silhouette"></div>${leagueLogo()}</div><div class="v11-video-copy"><h1>REPETICIÓN ◀◀ DEL PARTIDO</h1><p>Revive el partido completo de la Liga Municipal de Fútbol Juventino Rosas, Guanajuato.</p><div><button class="white" data-action="login">▣ Ver ahora</button><button>Partido de la Semana</button></div></div></section><div class="v11-dots"><i></i><i></i><i></i><i></i><i></i><i></i></div>${videoRail('Selección del editor','EL SHOW DE LA LIGA','america')}${videoRail('Resumen extendido','RESUMEN EXTENDIDO','huerta')}${videoRail('Momentos','MOMENTOS','galeana')}${videoRail('Repeticiones','REPETICIÓN DEL PARTIDO','lobos')}${miniVideo('Conferencias',['america','huerta','promesas'])}${miniVideo('Entrevistas',['galeana','lobos','franco'])}<section class="v11-video-season"><h2>Lo mejor de la temporada</h2><p>Revive los mejores goles, atajadas y momentos de la Liga Municipal de Fútbol Juventino Rosas.</p><button><b>JUGADOR<br>DESTACADO</b><span>▶ 30 vídeos</span></button></section><section class="v11-video-season"><h2>FINAL LOCAL</h2><button><b>MOMENTOS<br>DE LA FINAL</b><span>2025–2026</span></button></section></div>`}

function fantasyLogin(){return `<div class="v11-ref-pack v11-fantasy-login"><header><h1>Fantasy Football</h1></header><div class="v11-sponsorbar"><span>Patrocinado por</span>${leagueLogo()}</div><div class="v11-fantasy-photo"><span class="v11-fake-player p1"></span><span class="v11-fake-player p2"></span></div><section><h2>Inicia sesión para jugar al<br>Fantasy</h2><p>Inicia sesión para guardar tu equipo, unirte a ligas y recibir alertas importantes sobre plazos.</p><button data-route="profile">Inicia sesión para jugar</button><a data-action="fantasy-close">Iniciaré sesión después</a></section></div>`}
export function fantasyView(){if(uiState.fantasyLogin)return fantasyLogin();return `<div class="v11-ref-pack v11-fantasy"><div class="v11-fantasy-lines l1"></div><div class="v11-fantasy-lines l2"></div><div class="v11-fantasy-title"><h1>FANTASY</h1><b>LIGA MUNICIPAL DE FÚTBOL</b><strong>JUVENTINO ROSAS</strong><span>GUANAJUATO</span></div><div class="v11-sponsored"><span>Patrocinado por</span>${leagueLogo()}</div><button class="v11-fantasy-stage" data-action="fantasy-login"><div class="v11-shirts"><i>✚</i><i>✚</i><i>✚</i></div><div class="v11-pitch-lines"></div></button><div class="v11-stadium"><div></div></div></div>`}

export function moreView(){const items=[['star','Siguiendo','following'],['shield','Equipos','teams'],['perf','Performance Zone','video'],['cup','Máximo goleador','scorers'],['moments','Momentos','moments'],['chart','Datos','stats'],['game','Pronostica Seis','predictor'],['shield','Quiz Arena','quiz'],['moreless','Más O Menos','moreLess'],['cup','Hospitalidad','venues'],['cup','Rankings de la Liga','rankings'],['history','Historia','history'],['bag','Tienda','store'],['info','Sobre la Liga Municipal','profile']];return `<div class="v11-ref-pack v11-more"><section class="v11-more-head"><h1>Más</h1>${profileButton()}</section><div class="v11-more-logo">${leagueLogo()}</div><div class="v11-more-ball"></div><div class="v11-more-list">${items.map((x,i)=>`${i===6?'<h3>Gaming</h3>':i===9?'<h3>En el evento</h3>':i===10?'<h3>Explorar</h3>':''}<button data-route="${x[2]}">${icon(x[0])}<b>${x[1]}</b></button>`).join('')}</div><div class="v11-sponsors"><p>Patrocinadores oficiales de la Liga</p><div><span>JUVENTINO<br>ROSAS</span><span>Pasión<br>Local</span><span>NUESTRO<br>FÚTBOL</span><span>COMUNIDAD<br>EN ACCIÓN</span><span>DEPORTE<br>UNE</span></div><small>App oficial de la Liga</small>${leagueLogo()}</div></div>`}
