import {TEAMS,TEAM} from './data.js';
import {uiState} from './state.js';
import {crest,leagueLogo,innerHeader} from './helpers.js';
import {icon} from './icons.js';

export function followingView(){
  if(!uiState.followed.length)return `<div class="v11-ref-pack">${innerHeader('Siguiendo')}<section class="v11-empty-follow">${leagueLogo()}<h2>Sin equipos seguidos todavía</h2><p>Busca tu equipo de la Liga Municipal y síguelo para tenerlo siempre a la mano.</p><button data-route="teams">+ Añadir equipos</button></section></div>`;
  const t=TEAM(uiState.followed[0]);
  return `<div class="v11-ref-pack">${innerHeader('Siguiendo')}<div class="v11-follow-list"><button data-action="team-sheet" data-value="${t.id}">${crest(t.id)}<b>${t.name}</b><span>Siguiendo</span></button></div></div>`;
}

export function teamsView(){return `<div class="v11-ref-pack">${innerHeader('')}<div class="v11-search"><span>${icon('search')}</span><input placeholder="Buscar equipos" data-action="team-search"></div><h2 class="v11-list-title">Equipos en la competición</h2><div class="v11-teams-list">${TEAMS.map(t=>`<div data-team-name="${t.name.toLowerCase()}">${crest(t.id)}<b>${t.name}</b><button data-action="follow" data-value="${t.id}" class="${uiState.followed.includes(t.id)?'on':''}">${uiState.followed.includes(t.id)?'Siguiendo':'Seguir'}</button></div>`).join('')}</div></div>`}

const statCard=(title,values)=>`<article class="v11-stat-card"><h3>${title}</h3>${TEAMS.slice(0,5).map((t,i)=>`<div><span>${i+1}</span>${crest(t.id)}<b>${t.name}</b><strong>${values[i]}</strong></div>`).join('')}<button>Ver todos los ${uiState.statsTab==='player'?'jugadores':'equipos'} ›</button></article>`;
export function statsView(){const labels=['General','Estadísticas de equipo','Estadísticas de jugador'];return `<div class="v11-ref-pack v11-stats">${innerHeader('Estadísticas',true)}<p class="v11-phase-sub">Fase final</p><div class="v11-stats-tabs">${['general','team','player'].map((v,i)=>`<button data-action="stats-tab" data-value="${v}" class="${uiState.statsTab===v?'active':''}">${labels[i]}</button>`).join('')}</div><section><div class="v11-section-title"><h2>${uiState.statsTab==='player'?'Estadísticas de jugador':'Estadísticas de equipo'}</h2><button>Ver todo</button></div><div class="v11-stat-carousel">${statCard('Goles',[6,5,5,4,4])}${statCard(uiState.statsTab==='player'?'Asistencias':'Partidos disputados',[5,5,4,4,3])}</div></section></div>`}

export function momentsView(){return `<div class="v11-ref-pack v11-moments">${innerHeader('Momentos')}<div class="v11-moments-grid">${TEAMS.slice(0,8).map((t,i)=>`<button><div class="v11-moment-photo m${i}">${crest(t.id)}<span>NUEVO</span></div><b>${t.short}</b></button>`).join('')}</div></div>`}

export function scorersView(){const names=['Mateo Villalobos','Diego Ramírez','Carlos Mendoza','Iván López','Luis Beltrán','Ángel Rocha','Sergio Lara','Jorge Medina'];return `<div class="v11-ref-pack">${innerHeader('Máximo goleador')}<div class="v11-scorer-top">${crest('america')}<div><small>#1 MÁXIMO GOLEADOR</small><h2>Mateo Villalobos</h2><p>Club América Veteranos</p></div><strong>8 <span>goles</span></strong></div><div class="v11-scorer-list">${names.map((n,i)=>`<button><span>${i+1}</span>${crest(TEAMS[i%TEAMS.length].id)}<b>${n}<small>${TEAMS[i%TEAMS.length].name}</small></b><strong>${8-i}</strong></button>`).join('')}</div></div>`}

export function predictorView(){return `<div class="v11-ref-pack v11-predictor"><h1>PRONOSTICA<br>SEIS</h1><span class="v11-predict-sub">LIGA JUVENTINO</span><div class="v11-predict-sponsored">Patrocinado por<br>${leagueLogo()}</div><div class="v11-predict-stage"><div><b>2</b><b>?</b></div><div class="v11-predict-trophy">♕</div></div><div class="v11-stadium"><div></div></div></div>`}

export function quizView(){return `<div class="v11-ref-pack v11-quiz"><h1>QUIZ <span>✓</span><br>DE LA <b>LIGA</b></h1><p>JUVENTINO ROSAS</p><div class="v11-quiz-answers">${['A','B','C','D'].map((l,i)=>`<button data-action="quiz" data-value="${i}" class="${uiState.quizSelection===i?'selected':''}"><span>${l}</span><b>${['América Veteranos','La Huerta','Promesas FC','Atlético Galeana'][i]}</b></button>`).join('')}</div><div class="v11-stadium"><div></div></div></div>`}

export function moreLessView(){return `<div class="v11-ref-pack v11-moreless"><h1>MÁS<br><span>O</span> MENOS</h1><div class="v11-moreless-controls"><div><span>↑</span><i>${crest('america')}</i></div><div><span>↓</span><i>${crest('lobos')}</i></div></div>${leagueLogo()}<div class="v11-stadium"><div></div></div></div>`}

export function rankingsView(){return `<div class="v11-ref-pack v11-rankings">${innerHeader('Rankings de la Liga',true)}<p class="v11-phase-sub">Liga Municipal de Fútbol Juventino Rosas</p><div class="v11-rank-tabs"><button data-action="rank-tab" data-value="federations" class="${uiState.rankingsTab==='federations'?'active':''}">Federaciones</button><button data-action="rank-tab" data-value="clubs" class="${uiState.rankingsTab==='clubs'?'active':''}">Clubes</button></div><div class="v11-rank-filter"><button>Temporada⌄</button><button>2026/27⌄</button></div><div class="v11-ranking-card"><div class="head"><span>#</span><b>${uiState.rankingsTab==='clubs'?'CLUB':'FEDERACIÓN'}</b><strong>PUNTOS</strong></div>${TEAMS.slice(0,8).map((t,i)=>`<button><span>${i+1}</span>${crest(t.id)}<b>${t.name}<small>${t.id==='huerta'?'Cuenda':'Juventino Rosas, Gto.'}</small></b><strong>${(19-i*1.3).toFixed(3)}</strong><i>›</i></button>`).join('')}</div></div>`}

export function historyView(){return `<div class="v11-ref-pack v11-history">${innerHeader('Historia')}<div class="v11-history-tabs">${[['summary','Resumen'],['seasons','Temporadas'],['champions','Campeones'],['finals','Finales']].map(([v,l])=>`<button data-action="history-tab" data-value="${v}" class="${uiState.historyTab===v?'active':''}">${l}</button>`).join('')}</div><section><div class="v11-section-title"><h2>Buscar por temporada</h2><button>Ver todo</button></div><div class="v11-season-strip">${['2025/26','2024/25','2023/24','2022/23'].map((y,i)=>`<button>${crest(TEAMS[i].id)}<span>${y}</span></button>`).join('')}</div></section><article class="v11-history-hero"><div class="v11-history-trophy">♕</div><div><small>PALMARÉS</small><h2>La historia de nuestra Liga</h2><p>Liga Municipal de Fútbol Juventino Rosas</p></div></article><section><h2>Ver partidos clásicos</h2><div class="v11-classics">${['america','huerta','galeana'].map((id,i)=>`<button><div>${crest(id)}${icon('play')}</div><b>${['Final municipal histórica','Los diez mejores goles','Clásico de Juventino Rosas'][i]}</b></button>`).join('')}</div></section><section><h2>Estadísticas históricas</h2><article class="v11-titles"><h3>Más títulos</h3>${[['america',15],['huerta',7],['lobos',6]].map(([id,n],i)=>`<div><span>${i+1}</span>${crest(id)}<b>${TEAM(id).name}</b><strong>${n}</strong>${icon('cup')}</div>`).join('')}</article></section></div>`}

export function profileView(){return `<div class="v11-ref-pack v11-profile-page">${innerHeader('Perfil')}<article class="v11-profile-card"><div><h2>Liga Municipal<br>de Futbol</h2><b>Juventino Rosas, Gto.</b><p>Inicia sesión para personalizar tu experiencia, seguir equipos y recibir notificaciones.</p></div>${leagueLogo()}<div class="v11-profile-actions"><button data-action="login">Iniciar sesión</button><button data-action="login">Crear una cuenta</button></div></article><div class="v11-profile-menu"><button data-route="following">☆<span>Siguiendo</span>›</button><button data-route="notifications">♧<span>Notificaciones</span>›</button><button data-action="language">◎<span>Tu idioma preferido</span>›</button><button data-action="feedback">▤<span>Ayúdanos a mejorar</span>›</button><h3>Ajustes de privacidad</h3><button data-route="privacy">◉<span>Ajustes de privacidad</span>›</button></div></div>`}

const switchRow=(key,label)=>`<label><span>${label}</span><input type="checkbox" data-action="notify" data-value="${key}" ${uiState.notifications[key]?'checked':''}><i></i></label>`;
export function notificationsView(){return `<div class="v11-ref-pack">${innerHeader('Notificaciones')}<div class="v11-settings"><h3>Partidos</h3>${switchRow('goals','Goles')}${switchRow('kickoff','Inicio del partido')}${switchRow('final','Resultado final')}<h3>General</h3>${switchRow('news','Noticias')}${switchRow('video','Vídeos')}${switchRow('fantasy','Fantasy')}</div></div>`}

export function privacyView(){return `<div class="v11-ref-pack">${innerHeader('Ajustes de privacidad')}<div class="v11-privacy"><h2>Tu privacidad</h2><p>Configura las preferencias de la aplicación de la Liga Municipal.</p><button data-action="privacy-all">Aceptar todo</button><button data-action="privacy-none">Rechazar todo</button><button>Configuraciones</button></div></div>`}
