import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE);const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']});
let windowNoStories=true;const sampleStories=[{id:'story1',title:'Jornada de la Liga',kind:'story',mime:'image/png',placement:'all',category:'all',expires:Date.now()+86400000}];const root=path.resolve('dist');const store=new Map();let revision=0;
try{
const page=await browser.newPage({viewport:{width:412,height:915},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',err=>errors.push(err.message));
await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname==='app.test'){const file=path.join(root,url.pathname.replace(/^\/App-liga-\//,'/')==='/'?'index.html':url.pathname.replace(/^\/App-liga-\//,''));try{const ext=path.extname(file);return route.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'})[ext]||'application/octet-stream'})}catch{return route.fulfill({status:404,body:'missing'})}}
if(url.hostname.endsWith('chatgpt.site')){let data={};const req=route.request(),pathname=url.pathname;if(pathname==='/api/me')return route.fulfill({status:401,json:{error:'No autorizado'},headers:{'Access-Control-Allow-Origin':'*'}});else if(pathname==='/api/media')data={items:windowNoStories?[]:sampleStories};else if(pathname.startsWith('/api/match/')){if(req.method()==='PUT'){const b=req.postDataJSON();store.set(pathname,b.state);data={revision:++revision}}else data={state:store.get(pathname)||null,revision}}return route.fulfill({json:data,headers:{'Access-Control-Allow-Origin':'*'}})}
if(url.href.includes('/iframe_api'))return route.fulfill({contentType:'application/javascript',body:'window.YT={Player:class{constructor(e,c){this.config=c;this.time=20;this.muted=true;setTimeout(()=>c.events.onReady(),1)}unMute(){window.__unMuted=true}playVideo(){this.config.events.onStateChange({data:1})}pauseVideo(){this.config.events.onStateChange({data:2})}seekTo(t){this.time=t}getCurrentTime(){return this.time}destroy(){}}};window.onYouTubeIframeAPIReady()'});
return route.fulfill({body:'<html></html>',contentType:'text/html'});
});
await page.addInitScript(()=>{window.FaceDetector=class{async detect(){return [{boundingBox:{x:200,y:120,width:120,height:160},landmarks:[]}]}}});
await page.goto('http://app.test/App-liga-/#/home',{waitUntil:'domcontentloaded'});await page.waitForTimeout(400);
const original=await page.evaluate(async()=>{
 const circle=document.createElement('span');circle.id='test-circle';Object.assign(circle.style,{display:'inline-block',width:'100px',height:'100px',borderRadius:'50%',overflow:'hidden'});
 const square=document.createElement('span');square.id='test-square';Object.assign(square.style,{display:'inline-block',width:'100px',height:'100px'});
 for(const box of [circle,square]){const img=new Image();img.className='v576-player-photo';img.src='./assets/player-placeholder-3d.webp';box.append(img);document.querySelector('#screen').append(box);await img.decode()}
 window.LJR_FACE_FRAME.scan();return document.querySelector('#test-circle img').src;
});
await page.waitForFunction(()=>document.querySelector('#test-circle img').dataset.ljrCredentialFaceCrop==='1');
const result=await page.evaluate(()=>{const img=document.querySelector('#test-circle img'),frame=img.parentElement.getBoundingClientRect(),photo=img.getBoundingClientRect();const scale=photo.width/img.naturalWidth,detectorScale=Math.max(1,Math.max(img.naturalWidth,img.naturalHeight)/640);return {src:img.src,x:photo.x+260*detectorScale*scale-frame.x,y:photo.y+184*detectorScale*scale-frame.y,squareStyle:document.querySelector('#test-square img').getAttribute('style'),position:getComputedStyle(img).position}});
assert.equal(result.src,original);assert.ok(Math.abs(result.x-50)<1,JSON.stringify(result));assert.ok(Math.abs(result.y-50)<1,JSON.stringify(result));assert.equal(result.squareStyle,null);assert.equal(result.position,'absolute');assert.deepEqual(errors,[]);console.log('PASS: face centred from detected bounds, original image preserved, square photograph untouched.');
}finally{await browser.close()}
