import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE);const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']});
let windowNoStories=true;const sampleStories=[{id:'story1',title:'Jornada de la Liga',kind:'story',mime:'image/png',placement:'all',category:'all',expires:Date.now()+86400000}];const root=path.resolve('dist');const store=new Map();let revision=0;
try{
const page=await browser.newPage({viewport:{width:412,height:915},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',err=>errors.push(err.message));
await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname==='app.test'){const file=path.join(root,url.pathname.replace(/^\/App-liga-\//,'/')==='/'?'index.html':url.pathname.replace(/^\/App-liga-\//,''));try{const ext=path.extname(file);return route.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'})[ext]||'application/octet-stream'})}catch{return route.fulfill({status:404,body:'missing'})}}
if(url.hostname.endsWith('chatgpt.site')){let data={};const req=route.request(),pathname=url.pathname;if(pathname==='/api/me')return route.fulfill({status:401,json:{error:'No autorizado'},headers:{'Access-Control-Allow-Origin':'*'}});else if(pathname==='/api/media')data={items:windowNoStories?[]:sampleStories};else if(pathname.startsWith('/api/match/')){if(req.method()==='PUT'){const b=req.postDataJSON();store.set(pathname,b.state);data={revision:++revision}}else data={state:store.get(pathname)||null,revision}}return route.fulfill({json:data,headers:{'Access-Control-Allow-Origin':'*'}})}
if(url.href.includes('/iframe_api'))return route.fulfill({contentType:'application/javascript',body:'window.YT={Player:class{constructor(e,c){this.config=c;this.time=20;this.muted=true;setTimeout(()=>c.events.onReady(),1)}unMute(){window.__unMuted=true}playVideo(){this.config.events.onStateChange({data:1})}pauseVideo(){this.config.events.onStateChange({data:2})}seekTo(t){this.time=t}getCurrentTime(){return this.time}destroy(){}}};window.onYouTubeIframeAPIReady()'});
return route.fulfill({body:'<html></html>',contentType:'text/html'});
});
await page.goto('http://app.test/App-liga-/#/home',{waitUntil:'domcontentloaded'});await page.waitForTimeout(900);
assert.equal(await page.locator('[data-liga-media]').count(),0);
await page.evaluate(()=>location.hash='#/jrControl');await page.waitForSelector('[data-liga-tools]');assert.equal(await page.locator('[data-route="jrControl"]').first().isVisible(),false);
await page.evaluate(()=>location.hash='#/quizArena');await page.waitForSelector('[data-v531-view="hub"]');await page.screenshot({path:'/workspace/scratch/fbb5cf86cb95/quiz-hub-v612.png'});
await page.locator('[data-v531-quiz-start]').first().click();await page.waitForSelector('[data-v531-view="countdown"]');assert.equal(await page.locator('[data-quiz-countdown]').innerText(),'3');await page.locator('[data-v614-countdown-skip]').click();await page.waitForSelector('[data-v531-view="game"]');assert.equal(await page.locator('[data-v531-q-answer]').count(),4);const timer=await page.locator('[data-quiz-timer]').innerText();await page.waitForTimeout(1100);assert.ok(Number(await page.locator('[data-quiz-timer]').innerText())<Number(timer));
await page.locator('[data-quiz-half]').click();assert.equal(await page.locator('[data-v531-q-answer]:visible').count(),2);
await page.locator('[data-v531-quiz-close]').click();await page.waitForSelector('[data-v531-exit-cancel]');await page.locator('[data-v531-exit-cancel]').first().click();assert.equal(await page.locator('[data-v531-exit-confirm]').count(),0);
await page.waitForTimeout(300);await page.screenshot({path:'/workspace/scratch/fbb5cf86cb95/quiz-game-v612.png'});await page.locator('[data-v531-q-answer]:visible').first().click();await page.waitForSelector('[data-v531-view="result"]',{timeout:2500}).catch(async e=>{console.log('errors',errors);console.log('route',await page.evaluate(()=>location.hash));console.log('body',(await page.locator('body').innerText()).slice(-1800));console.log('layers',await page.evaluate(()=>document.elementsFromPoint(180,440).slice(0,8).map(x=>[x.tagName,x.className,getComputedStyle(x).opacity,getComputedStyle(x).background,x.outerHTML.slice(0,220)])));await page.screenshot({path:'/workspace/scratch/fbb5cf86cb95/quiz-error-v612.png'});throw e});
windowNoStories=false;await page.evaluate(()=>location.hash='#/moments');await page.evaluate(()=>window.LJR_MEDIA.refresh());await page.waitForSelector('[data-view="story1"]');await page.locator('[data-view="story1"]').click();await page.waitForSelector('.liga-story-picture');await page.locator('.liga-media-modal [data-close]').click();
await page.evaluate(()=>location.hash='#/safe-performance');await page.waitForSelector('[data-view="story1"]');
assert.deepEqual(errors,[]);console.log('PASS: no public admin card, protected editor routes, quiz hub/timer/turbo/exit/result, stories in Momentos and Performance.');
}finally{await browser.close()}
