import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
test('player statistics shows the official goal ranking with compact official player details',async()=>{
 const data=JSON.parse(fs.readFileSync(new URL('../data/official-live.json',import.meta.url)));
 const screen={innerHTML:'',querySelector:()=>null,addEventListener(){}};
 const window={LJR_OFFICIAL_DATA:data,addEventListener(){},scrollTo(){}};
 const document={readyState:'loading',body:{classList:{toggle(){},contains(){return false}}},querySelector:s=>s==='#screen'?screen:null,querySelectorAll:()=>[],addEventListener(){}};
 const context={window,document,location:{hash:'#/leagueData'},localStorage:{getItem:()=>null,setItem(){}},requestAnimationFrame:()=>1,MutationObserver:class{observe(){}},setTimeout};
 vm.runInNewContext(fs.readFileSync(new URL('../src/v33-data-statistics-reference.js',import.meta.url),'utf8'),context);
 await window.LJR_V33_STATS.setTab('player');
 assert.ok(!screen.innerHTML.includes('✓'),'no registration checkmarks in statistics');
 assert.ok(!screen.innerHTML.includes(' · Jugador registrado'),'only team and position in the secondary line');
 assert.match(screen.innerHTML,/<h2>Goles<\/h2>/);
 assert.deepEqual([...screen.innerHTML.matchAll(/<h2>([^<]+)<\/h2>/g)].map(m=>m[1]),['Datos clave','Goles','Remates','Ataque','Distribución','Defensa','Portería','Información disciplinaria']);
 const [first]=data.categories['3'].scorers[0].rows;
 const goalsCard=screen.innerHTML.split('data-v33-metric="goals"')[1]?.split('</article>')[0]||'';
 assert.ok(goalsCard.includes(first[1]),'official top scorer appears in the goals card');
 assert.ok(!goalsCard.includes('goles en temporada'),'team summaries never become player rankings');
 const shotsCard=screen.innerHTML.split('data-v33-metric="shots"')[1]?.split('</article>')[0]||'';
 assert.match(shotsCard,/Datos no publicados/);
 assert.ok([...shotsCard.matchAll(/<strong[^>]*>([^<]+)<\/strong>/g)].every(m=>m[1]==='—'),'unknown shots never inherit a player goal count');
 const yellow=screen.innerHTML.split('data-v33-metric="yellow"')[1]?.split('</article>')[0]||'';
 assert.ok(yellow.includes(data.categories['3'].cards[0].rows.find(r=>r[0]==='Amarilla')[1]),'disciplinary section contains published cards');
 const row=goalsCard.match(new RegExp('data-v33-player="'+first[1]+'"[^]*?<strong[^>]*>([^<]+)</strong>'));
 assert.equal(row?.[1],first[3],'goals are official numeric values, not registration check marks');
});
