import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE);const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox']});
const root=path.resolve('dist');const store=new Map();let revision=0;
try{
const page=await browser.newPage({viewport:{width:412,height:915},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',err=>errors.push(err.message));
await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname==='app.test'){const file=path.join(root,url.pathname.replace(/^\/App-liga-\//,'/')==='/'?'index.html':url.pathname.replace(/^\/App-liga-\//,''));try{const ext=path.extname(file);return route.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'})[ext]||'application/octet-stream'})}catch{return route.fulfill({status:404,body:'missing'})}}
if(url.hostname.endsWith('chatgpt.site')){let data={};const req=route.request(),pathname=url.pathname;if(pathname==='/api/me')data={admin:{id:'owner',name:'Presidente',owner:1}};else if(pathname==='/api/media')data={items:[]};else if(pathname.startsWith('/api/match/')){if(req.method()==='PUT'){const b=req.postDataJSON();store.set(pathname,b.state);data={revision:++revision}}else data={state:store.get(pathname)||null,revision}}return route.fulfill({json:data,headers:{'Access-Control-Allow-Origin':'*'}})}
if(url.href.includes('/iframe_api'))return route.fulfill({contentType:'application/javascript',body:'window.YT={Player:class{constructor(e,c){this.config=c;this.time=20;this.muted=true;setTimeout(()=>c.events.onReady(),1)}unMute(){window.__unMuted=true}playVideo(){this.config.events.onStateChange({data:1})}pauseVideo(){this.config.events.onStateChange({data:2})}seekTo(t){this.time=t}getCurrentTime(){return this.time}destroy(){}}};window.onYouTubeIframeAPIReady()'});
return route.fulfill({body:'<html></html>',contentType:'text/html'});
});
await page.goto('http://app.test/App-liga-/#/matchCenter',{waitUntil:'domcontentloaded'});await page.waitForSelector('[data-v144-operator]',{state:'attached'});assert.equal(await page.locator('[data-v144-operator]').isVisible(),false);assert.equal(await page.evaluate(()=>window.LJR_MATCH_LIVE.addEvent('goal','home')),null);
await page.evaluate(()=>{localStorage.setItem('liga-media-session','test');location.reload()});await page.waitForSelector('body.liga-editor');await page.waitForSelector('[data-v144-phase="phase-first"]');assert.equal(await page.locator('[data-v144-operator]').evaluate(e=>e.open),true);
await page.locator('[data-v144-phase="phase-first"]').click();await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>window.LJR_MATCH_LIVE.getState().phase),'first');
await page.locator('[data-v610-auto-voice]').check();await page.waitForTimeout(500);await page.evaluate(()=>window.LJR_MATCH_LIVE.analyze('Medio tiempo'));await page.waitForTimeout(450);assert.equal(await page.evaluate(()=>window.LJR_MATCH_LIVE.getState().phase),'halftime');
await page.evaluate(()=>window.LJR_MATCH_LIVE.analyze('Inicia el segundo tiempo'));await page.waitForTimeout(450);assert.equal(await page.evaluate(()=>window.LJR_MATCH_LIVE.getState().phase),'second');
const count=await page.evaluate(()=>window.LJR_MATCH_LIVE.getState().events.length);await page.evaluate(()=>window.LJR_MATCH_LIVE.analyze('No fue gol, el gol anulado no cuenta'));await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.LJR_MATCH_LIVE.getState().events.length),count);
await page.evaluate(()=>window.LJR_STREAM_CENTER.addSource('https://youtu.be/M7lc1UVf-VE','YouTube'));await page.waitForSelector('[data-v196-stream-hub] iframe');await page.waitForTimeout(300);await page.locator('[data-v196-stream-hub] [data-action=play]').click();assert.equal(await page.evaluate(()=>window.__unMuted),true);await page.locator('[data-v196-stream-hub] [data-v608-retry]').click();await page.waitForTimeout(300);assert.ok(await page.locator('[data-v196-stream-hub] [data-action=play]').count());
await page.evaluate(()=>location.hash='#/competition');await page.waitForSelector('[data-comp-tab=standings]');await page.locator('[data-comp-tab=standings]').click();await page.waitForSelector('[data-v40-standings]',{timeout:4000}).catch(async err=>{console.log((await page.locator('#screen').innerText()).slice(0,2500));console.log('errors',errors);throw err});for(const mode of ['compact','complete','criteria']){await page.locator('[data-v40-mode='+mode+']').click();await page.waitForTimeout(150);const widths=await page.locator('[data-v580-scroll]').evaluate(el=>{el.scrollLeft=200;return {client:el.clientWidth,scroll:el.scrollWidth,left:el.scrollLeft,row:el.querySelector('tr:not(.v580-section-row) td')?.getBoundingClientRect().height,team:getComputedStyle(el.querySelector('.teamname')).position}});assert.ok(widths.scroll>widths.client,JSON.stringify({mode,...widths}));assert.ok(widths.left>0,JSON.stringify({mode,...widths}));assert.equal(widths.team,'static');assert.ok(widths.row<=44,JSON.stringify({mode,...widths}));}
await page.screenshot({path:'/workspace/scratch/293375b42ee4/table-v610.png'});
await page.evaluate(()=>{const p=window.V66_OFFICIAL_DIRECTORY.playerList().find(x=>x.name.includes('Mario Eduardo'));window.LJR_PLAYER_PROFILE_API.open(p)});await page.waitForSelector('.v379-hero');await page.waitForTimeout(600);console.log('portrait',await page.locator('.v610-generic-player,.v580-player-hero-photo').evaluateAll(xs=>xs.map(i=>({src:i.src,current:i.currentSrc,width:i.naturalWidth,complete:i.complete}))));await page.waitForFunction(()=>[...document.querySelectorAll('.v610-generic-player,.v580-player-hero-photo')].some(i=>i.naturalWidth>0),{},{timeout:1500});assert.ok(await page.locator('.v610-generic-player,.v580-player-hero-photo').count());await page.screenshot({path:'/workspace/scratch/293375b42ee4/player-v610.png'});
await page.evaluate(()=>location.hash='#/video');await page.waitForSelector('[data-liga-media]');assert.equal(await page.locator('[data-edit]').isVisible(),true);assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: public/admin separation, open operator, auto narration, negation, YouTube sound/retry, three scrolling modes, player portrait and media editor.');
}finally{await browser.close()}
