// Liga Juventino V5 — Performance Zone, Datos, notifications and profile utilities.
(function(){
  const KEY='lj-store-v5', BASE_KEY='lj-store-v3';
  const screen=()=>document.querySelector('#screen');
  const back=()=>document.querySelector('#backButton');
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const read=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const defaults={dataTab:'General',performanceFilter:'Todos',language:'Español',feedbackType:'Sugerencia',feedback:[],consent:{essential:true,analytics:false,personalization:true,accepted:null},predictorSlide:0,cart:{},notificationPrefs:{fantasy:true,predictor:true,quiz:true,moreless:true,news:true,tickets:false,hospitality:false,video:true,transfers:true,goals:true,kickoff:true,final:true},inbox:[
    {id:'n1',title:'Juventino vs Pozos',body:'El partido destacado inicia hoy a las 18:00.',time:'Hoy',read:false,route:'match'},
    {id:'n2',title:'Nuevo video',body:'Ya puedes ver el resumen de la Jornada 5.',time:'Hoy',read:false,route:'video'},
    {id:'n3',title:'Fantasy',body:'Revisa tu 7 Ideal antes del cierre de la jornada.',time:'Ayer',read:true,route:'fantasy'}
  ]};
  let v5={...defaults,...read(KEY,{}),consent:{...defaults.consent,...(read(KEY,{}).consent||{})},notificationPrefs:{...defaults.notificationPrefs,...(read(KEY,{}).notificationPrefs||{})}};
  const save=()=>write(KEY,v5); const base=()=>read(BASE_KEY,{});
  const route=()=>location.hash.replace('#/',''); const isV5=()=>route().startsWith('v5-');
  const toast=t=>{const n=document.createElement('div');n.className='toast';n.textContent=t;document.body.appendChild(n);setTimeout(()=>n.remove(),1800)};
  const svg=(name)=>{const m={bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',chart:'<path d="M4 20V10M10 20V4M16 20v-7M22 20V7"/>',bolt:'<path d="m13 2-9 12h7l-1 8 9-12h-7z"/>',globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/>',msg:'<path d="M4 4h16v12H8l-4 4z"/>',shield:'<path d="M12 3 20 6v6c0 5-3 8-8 10-5-2-8-5-8-10V6z"/>',doc:'<path d="M6 3h9l3 3v15H6zM9 10h6M9 14h6"/>',ticket:'<path d="M4 7h16v10H4a2 2 0 0 0 0-4V7z"/>',bag:'<path d="M5 8h14l-1 13H6zM9 8V6a3 3 0 0 1 6 0v2"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',play:'<circle cx="12" cy="12" r="9"/><path d="m10 8 6 4-6 4z"/>',star:'<path d="m12 3 2.8 5.8 6.2.9-4.5 4.4 1.1 6.2L12 17.4 6.4 20.3l1.1-6.2L3 9.7l6.2-.9z"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21c1.6-4 4.3-6 8-6s6.4 2 8 6"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8z"/>',home:'<path d="M3 11.2 12 4l9 7.2V21h-6v-6H9v6H3z"/>',game:'<path d="M8 8h8l3 3v6l-3 2-2-3h-4l-2 3-3-2v-6zM8 12h4M10 10v4M16 12h.01"/>'};return `<svg class="v5-icon" viewBox="0 0 24 24" aria-hidden="true">${m[name]||m.info}</svg>`};
  const iconWrap=n=>`<span class="v5-menu-icon">${svg(n)}</span>`;
  const go=n=>{location.hash='#/'+n;render()};
  const goBase=n=>{location.hash='#/'+n};
  const teams=[{c:'JUV',n:'Juventino',p:13,g:9},{c:'POZ',n:'Pozos',p:11,g:6},{c:'RIN',n:'Rincón de Centeno',p:9,g:3},{c:'CUE',n:'Cuenda',p:8,g:1},{c:'SPD',n:'San Pedro',p:6,g:-1},{c:'MOR',n:'Morales',p:4,g:-4}];
  const players=[{n:'Juan Pérez',t:'JUV',goals:8,assists:3,min:420},{n:'Carlos Ramírez',t:'POZ',goals:6,assists:4,min:405},{n:'Miguel Torres',t:'RIN',goals:5,assists:5,min:440},{n:'Ángel Cruz',t:'CUE',goals:5,assists:2,min:390},{n:'Diego Lara',t:'SPD',goals:4,assists:4,min:430}];
  const crest=c=>`<span class="crest">${c}</span>`;
  function ensureTopbar(){const top=$('.topbar');if(!top)return;if(!$('#v5Bell',top)){const b=document.createElement('button');b.id='v5Bell';b.className='icon-button v5-bell';b.dataset.v5Route='v5-notifications';b.setAttribute('aria-label','Notificaciones');top.insertBefore(b,$('.profile-button',top));}updateBell()}
  function updateBell(){const b=$('#v5Bell');if(!b)return;const u=v5.inbox.filter(x=>!x.read).length;b.innerHTML=`${svg('bell')}${u?`<span class="v5-badge">${u}</span>`:''}`}
  function menuIconByText(t){t=t.toLowerCase();if(t.includes('notific'))return'bell';if(t.includes('dato')||t.includes('estad'))return'chart';if(t.includes('rendimiento')||t.includes('performance'))return'bolt';if(t.includes('idioma'))return'globe';if(t.includes('mejorar'))return'msg';if(t.includes('privacidad'))return'shield';if(t.includes('términ')||t.includes('reglamento'))return'doc';if(t.includes('hospital'))return'ticket';if(t.includes('tienda'))return'bag';if(t.includes('perfil')||t.includes('siguiendo'))return'user';if(t.includes('video')||t.includes('momento'))return'play';if(t.includes('fantasy')||t.includes('quiniela')||t.includes('quiz')||t.includes('menos'))return'game';return'info'}
  function iconizeMenus(){ $$('.menu-row').forEach(row=>{if(row.classList.contains('v5-iconized'))return;const text=row.textContent||'';row.classList.add('v5-iconized');row.insertAdjacentHTML('afterbegin',iconWrap(menuIconByText(text)))}) }
  function injectMore(){const root=screen();if(!root||route()!=='more'||$('#v5More',root))return;const block=document.createElement('div');block.id='v5More';block.className='menu-group';block.innerHTML=`<h3>EXPERIENCIA Y DATOS</h3><button class="menu-row" data-v5-route="v5-performance"><span>Performance Zone<small>Rendimiento, análisis y clips</small></span><span>›</span></button><button class="menu-row" data-v5-route="v5-data"><span>Datos<small>Estadísticas clave de equipos y jugadores</small></span><span>›</span></button><button class="menu-row" data-v5-route="v5-notifications"><span>Notificaciones<small>Equipos, juegos y avisos generales</small></span><span>›</span></button><button class="menu-row" data-v5-route="v5-hospitality"><span>En el evento<small>Acceso, sedes y experiencia de jornada</small></span><span>›</span></button><button class="menu-row" data-v5-route="v5-shop"><span>Tienda<small>Productos de Liga Juventino</small></span><span>›</span></button><button class="menu-row" data-v5-route="v5-about"><span>Sobre la competición<small>Formato, categorías y organización</small></span><span>›</span></button>`;root.appendChild(block);
    const pred=$('[data-route="predictor"]',root);if(pred){pred.dataset.v5Route='v5-predictor';delete pred.dataset.route}
    const notif=$('[data-route="notifications"]',root);if(notif){notif.dataset.v5Route='v5-notifications';delete notif.dataset.route}
    iconizeMenus();
  }
  function injectProfile(){const root=screen();if(!root||route()!=='profile'||$('#v5ProfileUtilities',root))return;const b=document.createElement('div');b.id='v5ProfileUtilities';b.className='menu-group';b.innerHTML=`<h3>CONFIGURACIÓN COMPLETA</h3><button class="menu-row" data-v5-route="v5-language"><span>Tu idioma preferido<small>${esc(v5.language)}</small></span><span>›</span></button><button class="menu-row" data-v5-route="v5-feedback"><span>Ayúdanos a mejorar<small>Errores, sugerencias y datos incorrectos</small></span><span>›</span></button><button class="menu-row" data-v5-route="v5-consent"><span>Ajustes de privacidad<small>Consentimiento y personalización</small></span><span>›</span></button><button class="menu-row" data-v5-route="v5-terms"><span>Términos y condiciones</span><span>›</span></button><button class="menu-row" data-v5-route="v5-privacy"><span>Política de privacidad</span><span>›</span></button>`;root.appendChild(b);iconizeMenus()}
  function injectBaseEnhancements(){ensureTopbar();injectMore();injectProfile();iconizeMenus()}
  function brand(title,sub=''){return `<div class="v5-brand-strip"><span class="eyebrow">LIGA JUVENTINO</span><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div>`}
  const performanceClips=[['El impacto del delantero centro','Ataque'],['La seguridad bajo los tres postes','Porteros'],['Velocidad en transición','Rendimiento'],['Presión alta y recuperación','Datos'],['La jugada de la jornada','Momentos']];
  function performanceView(){const f=v5.performanceFilter;const clips=f==='Todos'?performanceClips:performanceClips.filter(x=>x[1]===f);return `<div class="v5-performance-hero"><span class="eyebrow">ANÁLISIS DEPORTIVO</span><h1>Performance<br>Zone</h1><p>Rendimiento de Liga Juventino con clips, tendencias y datos de la jornada.</p></div><div class="v5-storyline">${['Jornada','Ataque','Porteros','Velocidad','Datos'].map(x=>`<button class="v5-story" data-v5-performance-filter="${x==='Jornada'?'Todos':x}"><span><i>${svg(x==='Porteros'?'shield':x==='Datos'?'chart':'bolt')}</i></span><small>${x}</small></button>`).join('')}</div><div class="v5-top-actions"><button class="btn ${f==='Todos'?'primary':'outline'}" data-v5-performance-filter="Todos">Todos</button><button class="btn ${f==='Ataque'?'primary':'outline'}" data-v5-performance-filter="Ataque">Ataque</button><button class="btn ${f==='Porteros'?'primary':'outline'}" data-v5-performance-filter="Porteros">Porteros</button></div><div class="v5-video-list">${clips.map((x,i)=>`<button class="v5-video-card" data-v5-video="${esc(x[0])}"><span class="v5-play">${svg('play')}</span><small>${x[1]} · ${8+i}:2${i}</small><strong>${x[0]}</strong></button>`).join('')}</div>`}
  function rankRows(list,key,label){return `<div class="v5-rank-card"><h3>${label}</h3>${list.map((x,i)=>`<div class="v5-rank-row"><b>${i+1}</b>${crest(x.t||x.c)}<span><b>${esc(x.n)}</b><small>${x.t?x.t:'Liga Juventino'}</small></span><b>${x[key]}</b></div>`).join('')}</div>`}
  function dataView(){let body='';if(v5.dataTab==='General')body=`<div class="v5-kpi-grid"><div class="v5-kpi"><b>42</b><span>Goles</span><small>Temporada actual</small></div><div class="v5-kpi"><b>15</b><span>Partidos</span><small>Registrados</small></div><div class="v5-kpi"><b>2.8</b><span>Goles / partido</span><small>Promedio</small></div><div class="v5-kpi"><b>6</b><span>Equipos</span><small>En categorías demo</small></div></div><section class="section">${rankRows(players.slice().sort((a,b)=>b.goals-a.goals),'goals','Máximos goleadores')}</section>`;if(v5.dataTab==='Equipos')body=`${rankRows(teams.slice().sort((a,b)=>b.p-a.p),'p','Puntos')}${rankRows(teams.slice().sort((a,b)=>b.g-a.g),'g','Diferencia de goles')}`;if(v5.dataTab==='Jugadores')body=`${rankRows(players.slice().sort((a,b)=>b.goals-a.goals),'goals','Goles')}${rankRows(players.slice().sort((a,b)=>b.assists-a.assists),'assists','Asistencias')}${rankRows(players.slice().sort((a,b)=>b.min-a.min),'min','Minutos')}`;return `${brand('Datos','Estadísticas clave de la competición, equipos y jugadores.')}<div class="v5-tabs">${['General','Equipos','Jugadores'].map(x=>`<button class="v5-tab ${v5.dataTab===x?'active':''}" data-v5-data-tab="${x}">${x}</button>`).join('')}</div>${body}<div class="v5-notice">Los valores mostrados son datos locales de demostración hasta conectar la base oficial de Liga Juventino.</div>`}
  function toggleRow(key,label,sub=''){return `<label class="v5-toggle-row"><span><b>${label}</b>${sub?`<small>${sub}</small>`:''}</span><input class="v5-switch" type="checkbox" data-v5-notif="${key}" ${v5.notificationPrefs[key]?'checked':''}></label>`}
  function notificationsView(){const followed=base().followed||[];return `${brand('Notificaciones','Elige exactamente qué quieres recibir.')}<div class="v5-setting-section"><div class="section-head"><h2>Bandeja</h2><button class="link-button" data-v5-action="read-all">Marcar todo leído</button></div>${v5.inbox.map(n=>`<button class="menu-row ${n.read?'':'unread'}" data-v5-inbox="${n.id}"><span><b>${esc(n.title)}</b><small>${esc(n.body)} · ${n.time}</small></span><span>›</span></button>`).join('')}</div><div class="v5-setting-section"><h2>Equipos</h2>${followed.length?followed.map(c=>toggleRow('team_'+c,`Alertas de ${c}`,'Goles, inicio y final de partido')).join(''):'<p class="muted tiny">Sigue equipos para recibir alertas específicas.</p>'}${toggleRow('goals','Goles','Avisos de gol de tus equipos seguidos')}${toggleRow('kickoff','Inicio de partido')}${toggleRow('final','Final del partido')}</div><div class="v5-setting-section"><h2>Juegos</h2>${toggleRow('fantasy','Fantasy Football')}${toggleRow('predictor','Quiniela')}${toggleRow('quiz','Quiz')}${toggleRow('moreless','Más o Menos')}</div><div class="v5-setting-section"><h2>General</h2>${toggleRow('news','Noticias')}${toggleRow('tickets','Ofertas de entradas y patrocinadores')}${toggleRow('hospitality','Hospitalidad / información del evento')}${toggleRow('video','Nuevo vídeo')}${toggleRow('transfers','Fichajes')}</div>`}
  const langs=['English','Français','Deutsch','Español','Português','Italiano'];
  function languageView(){return `${brand('Tu idioma preferido','Elige el idioma de la interfaz.')}<div class="v5-language-card">${langs.map(l=>`<label class="v5-radio-row"><input type="radio" name="v5lang" value="${l}" ${v5.language===l?'checked':''}><span>${l}</span></label>`).join('')}</div><p class="muted tiny" style="margin-top:12px">La app principal seguirá usando español hasta que se agreguen todas las traducciones.</p>`}
  function feedbackView(){return `${brand('Ayúdanos a mejorar','Tu comentario se guarda localmente en esta versión.')}<div class="v5-form"><div class="v5-option-grid">${['Reportar error','Sugerencia','Datos incorrectos','Problema de cuenta'].map(x=>`<button class="v5-option ${v5.feedbackType===x?'active':''}" data-v5-feedback-type="${x}">${x}</button>`).join('')}</div><textarea id="v5FeedbackText" placeholder="Cuéntanos qué debemos mejorar…"></textarea><button class="btn primary full" style="margin-top:10px" data-v5-action="send-feedback">Enviar comentario</button></div>${v5.feedback.length?`<section class="section"><h2>Enviados en este dispositivo</h2>${v5.feedback.slice(-3).reverse().map(f=>`<div class="v5-notice" style="margin-top:8px"><b>${esc(f.type)}</b><br>${esc(f.text)}</div>`).join('')}</section>`:''}`}
  function consentView(){return `${brand('Ajustes de privacidad','Controla consentimiento, analítica y personalización.')}<div class="v5-consent-card"><h2>Consentimiento para datos</h2><p class="v5-legal">La aplicación puede utilizar almacenamiento local para conservar preferencias, Fantasy, Quiniela y ajustes. La analítica y personalización opcionales deben depender de tu elección.</p>${toggleConsent('essential','Almacenamiento esencial','Necesario para conservar tus preferencias',true)}${toggleConsent('analytics','Analítica opcional','Ayuda a entender qué pantallas se usan')}${toggleConsent('personalization','Personalización','Ordena contenido según equipos seguidos')}<div class="button-row" style="margin-top:14px"><button class="btn primary" data-v5-action="accept-consent">Aceptar seleccionadas</button><button class="btn outline" data-v5-action="reject-consent">Solo esenciales</button></div></div>`}
  function toggleConsent(key,label,sub,disabled=false){return `<label class="v5-toggle-row"><span><b>${label}</b><small>${sub}</small></span><input class="v5-switch" type="checkbox" data-v5-consent="${key}" ${v5.consent[key]?'checked':''} ${disabled?'disabled':''}></label>`}
  function termsView(){return `${brand('Términos y condiciones','Versión de trabajo para Liga Juventino.')}<div class="v5-legal"><h2>Uso de la aplicación</h2><p>La aplicación ofrece información del torneo, resultados, juegos, Fantasy, Quiniela y contenido multimedia. Los datos oficiales deberán provenir de la administración de Liga Juventino.</p><h2>Cuentas y juegos</h2><p>Las funciones competitivas pueden requerir una cuenta cuando se conecte el backend. Las puntuaciones de demostración almacenadas en el teléfono no representan clasificaciones oficiales.</p><h2>Contenido</h2><p>Los logos, fotografías, videos y patrocinadores deberán ser contenido propio o autorizado por la Liga.</p></div>`}
  function privacyView(){return `${brand('Política de privacidad','Resumen claro de los datos usados por la aplicación.')}<div class="v5-legal"><h2>Datos locales</h2><p>Esta compilación guarda preferencias, favoritos, seguimiento, pronósticos y configuraciones en el dispositivo.</p><h2>Cuando conectemos Firebase</h2><p>La versión conectada deberá explicar qué datos de cuenta se almacenan, para qué se usan, cuánto tiempo se conservan y cómo solicitar su eliminación.</p><h2>Notificaciones</h2><p>Las preferencias de notificación pueden modificarse en cualquier momento desde la aplicación.</p></div>`}
  function predictorView(){const slides=[{t:'Pronostica tus resultados',d:'Elige marcadores para los partidos de cada jornada.',a:'2 — ?'},{t:'Suma puntos',d:'Consigue puntos por resultado correcto y marcador exacto.',a:'+3'},{t:'Enfréntate a tus amigos',d:'Compara tu puntuación en ligas privadas cuando conectemos cuentas.',a:'VS'}],s=slides[v5.predictorSlide];return `<div class="v5-predictor-stage"><span class="eyebrow">QUINIELA LIGA JUVENTINO</span><h1 class="game-title">PRONOSTICA</h1><div class="v5-slide-art"><strong>${s.a}</strong></div><h2 style="text-align:center">${s.t}</h2><p class="muted" style="text-align:center">${s.d}</p><div class="v5-dots">${slides.map((_,i)=>`<i class="${i===v5.predictorSlide?'active':''}"></i>`).join('')}</div><div class="button-row center"><button class="btn outline" data-v5-action="predictor-prev" ${v5.predictorSlide===0?'disabled':''}>Anterior</button><button class="btn primary" data-v5-action="predictor-next">${v5.predictorSlide===2?'Ir a jugar':'Siguiente'}</button></div><button class="btn outline full" style="margin-top:10px" data-v5-action="predictor-guest">Probar como invitado</button><button class="btn ghost full" style="margin-top:8px" data-v5-action="predictor-login">Iniciar sesión</button></div>`}
  function hospitalityView(){return `${brand('En el evento','Información práctica para vivir la jornada.')}<div class="v5-feature-grid"><div class="v5-tile">${iconWrap('ticket')}<b>Acceso</b><small>Horarios de apertura y recomendaciones de llegada.</small></div><div class="v5-tile">${iconWrap('home')}<b>Sedes</b><small>Campos y partidos programados.</small></div><div class="v5-tile">${iconWrap('info')}<b>Información</b><small>Reglamento de acceso y servicios disponibles.</small></div><div class="v5-tile">${iconWrap('heart')}<b>Experiencia</b><small>Contenido para aficionados durante la jornada.</small></div></div><p class="v5-notice" style="margin-top:14px">No se muestran servicios o accesos que Liga Juventino no haya confirmado oficialmente.</p>`}
  const products=[{id:'shirt',n:'Playera Liga Juventino',price:299},{id:'cap',n:'Gorra Liga Juventino',price:199},{id:'scarf',n:'Bufanda Liga Juventino',price:249}];
  function shopView(){const count=Object.values(v5.cart).reduce((a,b)=>a+b,0),total=products.reduce((s,p)=>s+(v5.cart[p.id]||0)*p.price,0);return `${brand('Tienda','Catálogo local de demostración.')}<div class="card v4-summary"><div><small>Productos</small><b>${count}</b></div><div><small>Total</small><b>$${total}</b></div></div><section class="section">${products.map(p=>`<div class="v5-cart-row"><span><b>${p.n}</b><small>$${p.price} MXN · Cantidad ${v5.cart[p.id]||0}</small></span><button class="mini-btn" data-v5-cart-add="${p.id}">+ Agregar</button></div>`).join('')}</section>${count?`<button class="btn primary full" data-v5-action="checkout">Finalizar pedido</button>`:''}<p class="muted tiny" style="margin-top:10px">El cobro real requerirá conectar un proveedor de pagos autorizado.</p>`}
  function aboutView(){return `${brand('Sobre la competición','Torneo Municipal Liga Juventino.')}<div class="v5-kpi-grid"><div class="v5-kpi"><b>6</b><span>Equipos demo</span><small>Escalable a más clubes</small></div><div class="v5-kpi"><b>2</b><span>Categorías</span><small>Primera Fuerza y Veteranos 35+</small></div></div><div class="v5-legal"><h2>Formato</h2><p>Calendario por jornadas, clasificación, estadísticas y cuadro eliminatorio cuando aplique.</p><h2>Identidad</h2><p>La aplicación usa branding propio de Liga Juventino y está preparada para sustituir datos demo por información oficial.</p></div>`}
  const views={'v5-performance':performanceView,'v5-data':dataView,'v5-notifications':notificationsView,'v5-language':languageView,'v5-feedback':feedbackView,'v5-consent':consentView,'v5-terms':termsView,'v5-privacy':privacyView,'v5-predictor':predictorView,'v5-hospitality':hospitalityView,'v5-shop':shopView,'v5-about':aboutView};
  function render(){if(!isV5())return;const root=screen();if(!root)return;root.innerHTML=(views[route()]||performanceView)();back()?.classList.remove('is-hidden');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.route==='more'));ensureTopbar();window.scrollTo(0,0)}
  function openVideo(title){const m=document.createElement('div');m.className='v5-modal';m.innerHTML=`<div class="v5-modal-card"><button class="v5-close" data-v5-close>×</button><div class="v5-modal-stage"><button aria-label="Reproducir">▶</button></div><span class="eyebrow">PERFORMANCE ZONE</span><h2>${esc(title)}</h2><p class="muted tiny">Reproductor preparado para conectar el video oficial de Liga Juventino.</p></div>`;document.body.appendChild(m)}
  function inboxOpen(id){const n=v5.inbox.find(x=>x.id===id);if(!n)return;n.read=true;save();updateBell();goBase(n.route)}
  document.addEventListener('click',e=>{
    const br=e.target.closest('#backButton');if(br&&isV5()){e.preventDefault();e.stopImmediatePropagation();goBase('more');return}
    const r=e.target.closest('[data-v5-route]');if(r){e.preventDefault();e.stopImmediatePropagation();go(r.dataset.v5Route);return}
    const f=e.target.closest('[data-v5-performance-filter]');if(f){v5.performanceFilter=f.dataset.v5PerformanceFilter;save();render();return}
    const dt=e.target.closest('[data-v5-data-tab]');if(dt){v5.dataTab=dt.dataset.v5DataTab;save();render();return}
    const ft=e.target.closest('[data-v5-feedback-type]');if(ft){v5.feedbackType=ft.dataset.v5FeedbackType;save();render();return}
    const vid=e.target.closest('[data-v5-video]');if(vid){openVideo(vid.dataset.v5Video);return}
    const close=e.target.closest('[data-v5-close]');if(close){e.target.closest('.v5-modal')?.remove();return}
    const inbox=e.target.closest('[data-v5-inbox]');if(inbox){inboxOpen(inbox.dataset.v5Inbox);return}
    const add=e.target.closest('[data-v5-cart-add]');if(add){v5.cart[add.dataset.v5CartAdd]=(v5.cart[add.dataset.v5CartAdd]||0)+1;save();toast('Producto agregado');render();return}
    const a=e.target.closest('[data-v5-action]');if(!a)return;const x=a.dataset.v5Action;
    if(x==='read-all'){v5.inbox.forEach(n=>n.read=true);save();updateBell();render()}
    if(x==='send-feedback'){const t=$('#v5FeedbackText')?.value.trim();if(!t)return toast('Escribe tu comentario');v5.feedback.push({type:v5.feedbackType,text:t,date:new Date().toISOString()});save();toast('Comentario guardado');render()}
    if(x==='accept-consent'){v5.consent.accepted=true;save();toast('Preferencias guardadas')}
    if(x==='reject-consent'){v5.consent={essential:true,analytics:false,personalization:false,accepted:true};save();toast('Solo almacenamiento esencial');render()}
    if(x==='predictor-prev'){v5.predictorSlide=Math.max(0,v5.predictorSlide-1);save();render()}
    if(x==='predictor-next'){if(v5.predictorSlide<2){v5.predictorSlide++;save();render()}else goBase('predictor')}
    if(x==='predictor-guest')goBase('predictor');if(x==='predictor-login')goBase('profile')
    if(x==='checkout')toast('Carrito listo; falta conectar pagos reales')
  },true);
  document.addEventListener('change',e=>{
    if(e.target.matches('[data-v5-notif]')){v5.notificationPrefs[e.target.dataset.v5Notif]=e.target.checked;save();toast('Preferencia guardada')}
    if(e.target.matches('[data-v5-consent]')){v5.consent[e.target.dataset.v5Consent]=e.target.checked;save()}
    if(e.target.matches('input[name="v5lang"]')){v5.language=e.target.value;save();toast('Idioma preferido guardado')}
  },true);
  window.addEventListener('hashchange',()=>setTimeout(()=>{if(isV5())render();else injectBaseEnhancements()},0));
  const obs=new MutationObserver(()=>{if(!isV5())injectBaseEnhancements();else ensureTopbar()});obs.observe(document.body,{childList:true,subtree:true});
  setTimeout(()=>{ensureTopbar();if(isV5())render();else injectBaseEnhancements()},0);
})();
