// Liga Juventino V6 — Home completo sin fotografías.
(function(){
  const screen=()=>document.querySelector('#screen');
  const route=()=>location.hash.replace('#/','')||'home';
  const icon=(name)=>{const p={news:'<path d="M5 4h14v16H5zM8 8h8M8 12h8M8 16h5"/>',play:'<circle cx="12" cy="12" r="9"/><path d="m10 8 6 4-6 4z"/>',star:'<path d="m12 3 2.8 5.8 6.2.9-4.5 4.4 1.1 6.2L12 17.4 6.4 20.3l1.1-6.2L3 9.7l6.2-.9z"/>',table:'<path d="M4 5h16v14H4zM4 10h16M9 5v14M15 5v14"/>',bolt:'<path d="m13 2-9 12h7l-1 8 9-12h-7z"/>',chart:'<path d="M4 20V10M10 20V4M16 20v-7M22 20V7"/>',calendar:'<path d="M5 4v3M19 4v3M4 8h16v12H4zM8 12h2M14 12h2M8 16h2M14 16h2"/>',trophy:'<path d="M8 4h8v4c0 3-1.5 5-4 6-2.5-1-4-3-4-6zM8 6H4v2c0 2.2 1.3 4 3.5 4.5M16 6h4v2c0 2.2-1.3 4-3.5 4.5M12 14v4M8 21h8"/>',team:'<path d="M7 5 3 7l2 4 2-1v9h10v-9l2 1 2-4-4-2c-.7 1.4-2.3 2-5 2s-4.3-.6-5-2z"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',data:'<circle cx="12" cy="12" r="9"/><path d="M8 14v3M12 10v7M16 7v10"/>',history:'<path d="M4 12a8 8 0 1 0 3-6M4 4v6h6M12 8v5l3 2"/>'};return `<svg class="v6-svg" viewBox="0 0 24 24" aria-hidden="true">${p[name]||p.data}</svg>`};
  const crest=(c)=>`<span class="v6-crest">${c}</span>`;
  const teams=[['JUV','Juventino',13,5,9],['POZ','Pozos',11,5,6],['RIN','Rincón de Centeno',9,5,3],['CUE','Cuenda',8,5,1],['SPD','San Pedro',6,5,-1],['MOR','Morales',4,5,-4]];
  const scorers=[['Juan Pérez','JUV',8],['Carlos Ramírez','POZ',6],['Miguel Torres','RIN',5],['Ángel Cruz','CUE',5]];
  const videos=[['Precisión a balón parado','Técnica · 00:21'],['Definición rápida','Ataque · 00:18'],['Transición y presión','Rendimiento · 00:26']];
  const news=[['Jornada 5','Todo listo para la próxima fecha'],['Liga','Horarios y sedes confirmados'],['Fichajes','Movimientos antes del cierre']];
  const actionCard=(iconName,title,sub,routeName)=>`<button class="v6-action-card" data-v6-route="${routeName}"><span class="v6-action-icon">${icon(iconName)}</span><span><b>${title}</b><small>${sub}</small></span><span class="v6-arrow">›</span></button>`;
  function homeHtml(){return `<div id="v6HomeSuper" class="v6-home-super">
    <section class="v6-section v6-quick"><div class="v6-section-head"><div><span class="eyebrow">TODO EN INICIO</span><h2>Explora Liga Juventino</h2></div><button class="v6-icon-btn" data-v6-route="v5-notifications" aria-label="Notificaciones">${icon('bell')}</button></div><div class="v6-action-grid">${actionCard('bolt','Performance Zone','Análisis y rendimiento','v5-performance')}${actionCard('data','Datos','Equipos y jugadores','v5-data')}${actionCard('calendar','Calendario','Fechas y resultados','v4-calendar')}${actionCard('star','Jugador de la Jornada','Vota y consulta candidatos','vote')}</div></section>

    <section class="v6-section"><div class="v6-section-head"><h2>Noticias</h2><button class="link-button" data-v6-route="news">Ver todo</button></div><div class="v6-news-strip">${news.map((n,i)=>`<button class="v6-news-card" data-v6-route="news"><span>${icon('news')}</span><small>${n[0]}</small><b>${n[1]}</b><em>${i===0?'Hoy':i===1?'Ayer':'Hace 2 días'}</em></button>`).join('')}</div></section>

    <section class="v6-section"><div class="v6-section-head"><h2>Vídeos destacados</h2><button class="link-button" data-v6-route="video">Ver todo</button></div><div class="v6-video-list">${videos.map(v=>`<button class="v6-video-card" data-v6-route="video"><span class="v6-play">${icon('play')}</span><small>${v[1]}</small><b>${v[0]}</b></button>`).join('')}</div></section>

    <section class="v6-section"><div class="v6-week-player"><span class="v6-kicker">JUGADOR DE LA SEMANA</span><div class="v6-week-row"><div class="v6-number">09</div><div><h3>Juan Pérez</h3><p>Juventino · 8 goles · 3 asistencias</p></div></div><div class="v6-week-actions"><button class="btn primary" data-v6-route="vote">Votar</button><button class="btn outline" data-v6-route="scorers">Ver goleadores</button></div></div></section>

    <section class="v6-section"><div class="v6-section-head"><h2>Clasificación</h2><button class="link-button" data-v6-route="competition">Ver completa</button></div><div class="v6-table-card"><div class="v6-table-head"><span>#</span><span>Equipo</span><span>PJ</span><span>DG</span><span>PTS</span></div>${teams.map((t,i)=>`<button class="v6-table-row" data-v6-route="competition"><span>${i+1}</span><span>${crest(t[0])}<b>${t[1]}</b></span><span>${t[3]}</span><span>${t[4]>0?'+':''}${t[4]}</span><strong>${t[2]}</strong></button>`).join('')}</div></section>

    <section class="v6-section"><button class="v6-performance-card" data-v6-route="v5-performance"><span class="v6-performance-icon">${icon('bolt')}</span><span><small>ANÁLISIS DE LA JORNADA</small><b>Performance Zone</b><p>Rendimiento, tendencias y clips tácticos.</p></span><span>›</span></button></section>

    <section class="v6-section"><div class="v6-section-head"><h2>Estadísticas de equipo</h2><button class="link-button" data-v6-route="stats">Ver todo</button></div><div class="v6-stat-carousel"><div class="v6-stat-card"><small>GOLES</small><b class="v6-big">14</b><p>Juventino</p><div class="v6-mini-bar"><i style="width:88%"></i></div></div><div class="v6-stat-card"><small>MEJOR DIFERENCIA</small><b class="v6-big">+9</b><p>Juventino</p><div class="v6-mini-bar"><i style="width:76%"></i></div></div><div class="v6-stat-card"><small>PUNTOS</small><b class="v6-big">13</b><p>Juventino</p><div class="v6-mini-bar"><i style="width:82%"></i></div></div></div><div class="v6-demo-note">Datos locales de demostración hasta conectar la base oficial.</div></section>

    <section class="v6-section"><div class="v6-section-head"><h2>Máximos goleadores</h2><button class="link-button" data-v6-route="scorers">Ver ranking</button></div><div class="v6-scorers">${scorers.map((s,i)=>`<button data-v6-route="scorers"><span class="v6-rank">${i+1}</span>${crest(s[1])}<span><b>${s[0]}</b><small>${s[1]}</small></span><strong>${s[2]}</strong></button>`).join('')}</div></section>

    <section class="v6-section"><div class="v6-section-head"><h2>Equipo de la Semana</h2><button class="link-button" data-v6-action="week-team">Ver equipo</button></div><button class="v6-teamweek" data-v6-action="week-team"><span>${icon('team')}</span><div><b>XI de la Jornada 5</b><p>Formación destacada basada en los datos disponibles.</p></div><span>›</span></button></section>

    <section class="v6-section"><div class="v6-section-head"><h2>Calendario y resultados</h2><button class="link-button" data-v6-route="v4-calendar">Abrir calendario</button></div><div class="v6-calendar-card"><div><span>12</span><small>OCT</small><b>RIN 1–3 JUV</b></div><div class="active"><span>13</span><small>OCT</small><b>JUV 1–0 POZ</b></div><div><span>14</span><small>OCT</small><b>SPD · MOR 19:00</b></div></div></section>

    <section class="v6-section"><div class="v6-section-head"><h2>Más datos</h2></div><div class="v6-action-grid">${actionCard('chart','Estadísticas','General, equipos y jugadores','stats')}${actionCard('trophy','Rankings','Clasificación y líderes','rankings')}${actionCard('history','Historia','Temporadas y campeones','history')}${actionCard('data','Datos avanzados','KPIs y comparativas','v5-data')}</div></section>

    <section class="v6-section"><div class="v6-sponsor-placeholder"><span>${icon('star')}</span><div><b>Patrocinadores oficiales</b><p>Este espacio se mostrará únicamente cuando existan patrocinadores confirmados.</p></div></div></section>
  </div>`}
  function showWeekTeam(){const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="video-modal v6-week-modal"><button class="modal-close">×</button><span class="eyebrow">EQUIPO DE LA SEMANA</span><h2>XI Jornada 5</h2><div class="v6-lineup"><b>POR</b><span>Jorge Medina · RIN</span><b>DEF</b><span>Luis Gómez · JUV</span><span>Iván Sánchez · POZ</span><span>Óscar León · MOR</span><b>MED</b><span>Edgar Ruiz · JUV</span><span>Miguel Torres · RIN</span><span>Sergio Luna · POZ</span><b>DEL</b><span>Juan Pérez · JUV</span><span>Carlos Ramírez · POZ</span><span>Ángel Cruz · CUE</span></div><button class="btn outline full" data-close-week>Cerrar</button></div>`;document.body.appendChild(modal);modal.querySelector('.modal-close').onclick=()=>modal.remove();modal.querySelector('[data-close-week]').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()}}
  function enhance(){if(route()!=='home')return;const root=screen();if(!root||root.querySelector('#v6HomeSuper'))return;root.insertAdjacentHTML('beforeend',homeHtml());}
  document.addEventListener('click',e=>{const r=e.target.closest('[data-v6-route]');if(r){e.preventDefault();location.hash='#/'+r.dataset.v6Route;return}const a=e.target.closest('[data-v6-action]');if(a?.dataset.v6Action==='week-team'){e.preventDefault();showWeekTeam()}});
  const mo=new MutationObserver(()=>enhance());mo.observe(document.querySelector('#screen'),{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(enhance,0));enhance();
})();