// Liga Juventino V6.1 — safe runtime. No MutationObserver and no global prototype patches.
(function(){
  'use strict';
  const screen=()=>document.querySelector('#screen');
  const back=()=>document.querySelector('#backButton');
  const route=()=>location.hash.replace('#/','')||'home';
  const KEY='lj-store-v61';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
  const state=Object.assign({dataTab:'General',performanceFilter:'Todos',language:'Español',feedback:[],notif:{goals:true,kickoff:true,final:true,news:true,video:true,fantasy:true,predictor:true,transfers:true},inbox:[{id:'a',title:'Jornada 5 lista',body:'Consulta horarios y sedes.',read:false,go:'competition'},{id:'b',title:'Nuevo resumen',body:'Ya está disponible el video de la jornada.',read:false,go:'video'},{id:'c',title:'Fantasy',body:'Revisa tu 7 Ideal antes del cierre.',read:true,go:'fantasy'}]},read());
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const svg=(name)=>{const p={bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',news:'<path d="M5 4h14v16H5zM8 8h8M8 12h8M8 16h5"/>',play:'<circle cx="12" cy="12" r="9"/><path d="m10 8 6 4-6 4z"/>',star:'<path d="m12 3 2.8 5.8 6.2.9-4.5 4.4 1.1 6.2L12 17.4 6.4 20.3l1.1-6.2L3 9.7l6.2-.9z"/>',bolt:'<path d="m13 2-9 12h7l-1 8 9-12h-7z"/>',chart:'<path d="M4 20V10M10 20V4M16 20v-7M22 20V7"/>',calendar:'<path d="M5 4v3M19 4v3M4 8h16v12H4zM8 12h2M14 12h2M8 16h2M14 16h2"/>',trophy:'<path d="M8 4h8v4c0 3-1.5 5-4 6-2.5-1-4-3-4-6zM8 6H4v2c0 2.2 1.3 4 3.5 4.5M16 6h4v2c0 2.2-1.3 4-3.5 4.5M12 14v4M8 21h8"/>',team:'<path d="M7 5 3 7l2 4 2-1v9h10v-9l2 1 2-4-4-2c-.7 1.4-2.3 2-5 2s-4.3-.6-5-2z"/>',globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/>',shield:'<path d="M12 3 20 6v6c0 5-3 8-8 10-5-2-8-5-8-10V6z"/>',msg:'<path d="M4 4h16v12H8l-4 4z"/>',doc:'<path d="M6 3h9l3 3v15H6zM9 10h6M9 14h6"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',history:'<path d="M4 12a8 8 0 1 0 3-6M4 4v6h6M12 8v5l3 2"/>'};return `<svg class="safe-svg" viewBox="0 0 24 24" aria-hidden="true">${p[name]||p.info}</svg>`};
  const crest=c=>`<span class="v6-crest">${c}</span>`;
  const teams=[['JUV','Juventino',13,5,9],['POZ','Pozos',11,5,6],['RIN','Rincón de Centeno',9,5,3],['CUE','Cuenda',8,5,1],['SPD','San Pedro',6,5,-1],['MOR','Morales',4,5,-4]];
  const scorers=[['Juan Pérez','JUV',8,3],['Carlos Ramírez','POZ',6,4],['Miguel Torres','RIN',5,5],['Ángel Cruz','CUE',5,2]];
  const actionCard=(ico,title,sub,to)=>`<button class="v6-action-card" data-safe-route="${to}"><span class="v6-action-icon">${svg(ico)}</span><span><b>${title}</b><small>${sub}</small></span><span class="v6-arrow">›</span></button>`;
  function ensureBell(){const top=document.querySelector('.topbar');if(!top)return;let b=document.querySelector('#safeBell');if(!b){b=document.createElement('button');b.id='safeBell';b.className='icon-button v5-bell';b.setAttribute('aria-label','Notificaciones');b.dataset.safeRoute='safe-notifications';const profile=top.querySelector('.profile-button');profile?top.insertBefore(b,profile):top.appendChild(b)}const unread=state.inbox.filter(x=>!x.read).length;const html=`${svg('bell')}${unread?`<span class="v5-badge">${unread}</span>`:''}`;if(b.innerHTML!==html)b.innerHTML=html}
  function homeExtra(){return `<div id="safeHomeExtra" class="v6-home-super">
    <section class="v6-section v6-quick"><div class="v6-section-head"><div><span class="eyebrow">TODO EN INICIO</span><h2>Explora Liga Juventino</h2></div><button class="v6-icon-btn" data-safe-route="safe-notifications" aria-label="Notificaciones">${svg('bell')}</button></div><div class="v6-action-grid">${actionCard('bolt','Performance Zone','Análisis y rendimiento','safe-performance')}${actionCard('chart','Datos','Equipos y jugadores','safe-data')}${actionCard('calendar','Calendario','Fechas y resultados','v4-calendar')}${actionCard('star','Jugador de la Jornada','Vota y consulta candidatos','vote')}</div></section>
    <section class="v6-section"><div class="v6-section-head"><h2>Noticias</h2><button class="link-button" data-safe-route="news">Ver todo</button></div><div class="v6-news-strip"><button class="v6-news-card" data-safe-route="news"><span>${svg('news')}</span><small>JORNADA 5</small><b>Todo listo para la próxima fecha</b><em>Hoy</em></button><button class="v6-news-card" data-safe-route="news"><span>${svg('news')}</span><small>LIGA</small><b>Horarios y sedes confirmados</b><em>Ayer</em></button><button class="v6-news-card" data-safe-route="transfers"><span>${svg('news')}</span><small>FICHAJES</small><b>Movimientos antes del cierre</b><em>Hace 2 días</em></button></div></section>
    <section class="v6-section"><div class="v6-section-head"><h2>Vídeos destacados</h2><button class="link-button" data-safe-route="video">Ver todo</button></div><div class="v6-video-list"><button class="v6-video-card" data-safe-route="video"><span class="v6-play">${svg('play')}</span><small>Técnica · 00:21</small><b>Precisión a balón parado</b></button><button class="v6-video-card" data-safe-route="video"><span class="v6-play">${svg('play')}</span><small>Ataque · 00:18</small><b>Definición rápida</b></button><button class="v6-video-card" data-safe-route="safe-performance"><span class="v6-play">${svg('play')}</span><small>Rendimiento · 00:26</small><b>Transición y presión</b></button></div></section>
    <section class="v6-section"><div class="v6-week-player"><span class="v6-kicker">JUGADOR DE LA SEMANA</span><div class="v6-week-row"><div class="v6-number">09</div><div><h3>Juan Pérez</h3><p>Juventino · 8 goles · 3 asistencias</p></div></div><div class="v6-week-actions"><button class="btn primary" data-safe-route="vote">Votar</button><button class="btn outline" data-safe-route="scorers">Ver goleadores</button></div></div></section>
    <section class="v6-section"><div class="v6-section-head"><h2>Clasificación</h2><button class="link-button" data-safe-route="competition">Ver completa</button></div><div class="v6-table-card"><div class="v6-table-head"><span>#</span><span>Equipo</span><span>PJ</span><span>DG</span><span>PTS</span></div>${teams.map((t,i)=>`<button class="v6-table-row" data-safe-route="competition"><span>${i+1}</span><span>${crest(t[0])}<b>${t[1]}</b></span><span>${t[3]}</span><span>${t[4]>0?'+':''}${t[4]}</span><strong>${t[2]}</strong></button>`).join('')}</div></section>
    <section class="v6-section"><button class="v6-performance-card" data-safe-route="safe-performance"><span class="v6-performance-icon">${svg('bolt')}</span><span><small>ANÁLISIS DE LA JORNADA</small><b>Performance Zone</b><p>Rendimiento, tendencias y clips tácticos.</p></span><span>›</span></button></section>
    <section class="v6-section"><div class="v6-section-head"><h2>Estadísticas de equipo</h2><button class="link-button" data-safe-route="stats">Ver todo</button></div><div class="v6-stat-carousel"><div class="v6-stat-card"><small>GOLES</small><b class="v6-big">14</b><p>Juventino</p><div class="v6-mini-bar"><i style="width:88%"></i></div></div><div class="v6-stat-card"><small>MEJOR DIFERENCIA</small><b class="v6-big">+9</b><p>Juventino</p><div class="v6-mini-bar"><i style="width:76%"></i></div></div><div class="v6-stat-card"><small>PUNTOS</small><b class="v6-big">13</b><p>Juventino</p><div class="v6-mini-bar"><i style="width:82%"></i></div></div></div><div class="v6-demo-note">Datos locales de demostración hasta conectar la base oficial.</div></section>
    <section class="v6-section"><div class="v6-section-head"><h2>Máximos goleadores</h2><button class="link-button" data-safe-route="scorers">Ver ranking</button></div><div class="v6-scorers">${scorers.map((s,i)=>`<button data-safe-route="scorers"><span class="v6-rank">${i+1}</span>${crest(s[1])}<span><b>${s[0]}</b><small>${s[1]}</small></span><strong>${s[2]}</strong></button>`).join('')}</div></section>
    <section class="v6-section"><div class="v6-section-head"><h2>Equipo de la Semana</h2><button class="link-button" data-safe-action="week-team">Ver equipo</button></div><button class="v6-teamweek" data-safe-action="week-team"><span>${svg('team')}</span><div><b>XI de la Jornada 5</b><p>Formación destacada basada en los datos disponibles.</p></div><span>›</span></button></section>
    <section class="v6-section"><div class="v6-section-head"><h2>Calendario y resultados</h2><button class="link-button" data-safe-route="v4-calendar">Abrir calendario</button></div><div class="v6-calendar-card"><div><span>12</span><small>OCT</small><b>RIN 1–3 JUV</b></div><div class="active"><span>13</span><small>OCT</small><b>JUV 1–0 POZ</b></div><div><span>14</span><small>OCT</small><b>SPD · MOR 19:00</b></div></div></section>
    <section class="v6-section"><div class="v6-section-head"><h2>Más datos</h2></div><div class="v6-action-grid">${actionCard('chart','Estadísticas','General, equipos y jugadores','stats')}${actionCard('trophy','Rankings','Clasificación y líderes','rankings')}${actionCard('history','Historia','Temporadas y campeones','history')}${actionCard('chart','Datos avanzados','KPIs y comparativas','safe-data')}</div></section>
  </div>`}
  function performanceView(){const filter=state.performanceFilter;const clips=[['Ataque','El impacto del delantero centro'],['Porteros','La seguridad bajo los tres postes'],['Rendimiento','Velocidad en transición'],['Datos','Presión alta y recuperación']].filter(x=>filter==='Todos'||x[0]===filter);return `<div class="safe-brand"><span class="eyebrow">ANÁLISIS DEPORTIVO</span><h1>Performance Zone</h1><p>Rendimiento, tendencias y clips de la jornada.</p></div><div class="safe-chipbar">${['Todos','Ataque','Porteros','Rendimiento','Datos'].map(x=>`<button class="chip ${filter===x?'selected':''}" data-safe-filter="${x}">${x}</button>`).join('')}</div><div class="safe-card-list">${clips.map(x=>`<button class="safe-media" data-safe-route="video"><span>${svg('play')}</span><small>${x[0]}</small><b>${x[1]}</b></button>`).join('')}</div><div class="safe-note">Los clips son placeholders hasta agregar videos oficiales.</div>`}
  function dataView(){const tab=state.dataTab;return `<div class="safe-brand"><span class="eyebrow">LIGA JUVENTINO</span><h1>Datos</h1><p>Estadísticas principales de equipos y jugadores.</p></div><div class="safe-tabs">${['General','Equipos','Jugadores'].map(x=>`<button class="${tab===x?'active':''}" data-safe-data-tab="${x}">${x}</button>`).join('')}</div>${tab==='General'?`<div class="safe-kpis"><div><b>42</b><small>Goles</small></div><div><b>15</b><small>Partidos</small></div><div><b>2.8</b><small>Goles / partido</small></div><div><b>6</b><small>Equipos</small></div></div>`:''}${tab==='Equipos'?`<div class="v6-table-card">${teams.map((t,i)=>`<div class="safe-rank"><b>${i+1}</b>${crest(t[0])}<span>${t[1]}</span><strong>${t[2]} pts</strong></div>`).join('')}</div>`:''}${tab==='Jugadores'?`<div class="v6-table-card">${scorers.map((s,i)=>`<div class="safe-rank"><b>${i+1}</b>${crest(s[1])}<span>${s[0]}</span><strong>${s[2]} G · ${s[3]} A</strong></div>`).join('')}</div>`:''}<div class="safe-note">Datos de demostración hasta conectar la base oficial.</div>`}
  function notificationsView(){return `<div class="safe-brand"><span class="eyebrow">ALERTAS</span><h1>Notificaciones</h1><p>Configura qué quieres recibir.</p></div><div class="safe-inbox">${state.inbox.map(n=>`<button class="${n.read?'read':''}" data-safe-inbox="${n.id}"><span>${svg('bell')}</span><div><b>${esc(n.title)}</b><small>${esc(n.body)}</small></div></button>`).join('')}</div><section class="section"><div class="section-head"><h2>Preferencias</h2></div>${[['goals','Goles'],['kickoff','Inicio del partido'],['final','Final del partido'],['news','Noticias'],['video','Nuevo vídeo'],['fantasy','Fantasy'],['predictor','Quiniela'],['transfers','Fichajes']].map(([k,l])=>`<label class="safe-toggle"><span>${l}</span><input type="checkbox" data-safe-notif="${k}" ${state.notif[k]?'checked':''}></label>`).join('')}</section>`}
  function simpleView(title,iconName,body){return `<div class="safe-brand"><span>${svg(iconName)}</span><h1>${title}</h1><p>${body}</p></div><button class="btn outline full" data-safe-route="profile">Volver a Perfil</button>`}
  const customViews={'safe-performance':performanceView,'safe-data':dataView,'safe-notifications':notificationsView,'safe-language':()=>simpleView('Idioma','globe',`Idioma preferido: ${state.language}. La app está preparada para español y futuras traducciones.`),'safe-feedback':()=>simpleView('Ayúdanos a mejorar','msg','Puedes reportar errores, sugerencias o datos incorrectos desde esta sección.'),'safe-privacy':()=>simpleView('Privacidad','shield','Las preferencias y datos demo se guardan localmente en este dispositivo hasta conectar el backend oficial.'),'safe-terms':()=>simpleView('Términos y condiciones','doc','Consulta aquí las reglas de uso de Liga Juventino.'),'safe-about':()=>simpleView('Sobre la competición','info','Torneo Municipal Liga Juventino: partidos, clasificación, estadísticas, Fantasy, juegos y contenido.')};
  function injectMore(){const root=screen();if(!root||route()!=='more'||root.querySelector('#safeMore'))return;const box=document.createElement('div');box.id='safeMore';box.className='menu-group';box.innerHTML=`<h3>EXPERIENCIA Y DATOS</h3><button class="menu-row" data-safe-route="safe-performance"><span>Performance Zone<small>Análisis y rendimiento</small></span><span>›</span></button><button class="menu-row" data-safe-route="safe-data"><span>Datos<small>Equipos y jugadores</small></span><span>›</span></button><button class="menu-row" data-safe-route="safe-notifications"><span>Notificaciones<small>Partidos, juegos y noticias</small></span><span>›</span></button><button class="menu-row" data-safe-route="safe-about"><span>Sobre la competición</span><span>›</span></button>`;root.appendChild(box)}
  function injectProfile(){const root=screen();if(!root||route()!=='profile'||root.querySelector('#safeProfile'))return;const box=document.createElement('div');box.id='safeProfile';box.className='menu-group';box.innerHTML=`<h3>CONFIGURACIÓN</h3><button class="menu-row" data-safe-route="safe-language"><span>Idioma preferido<small>${state.language}</small></span><span>›</span></button><button class="menu-row" data-safe-route="safe-feedback"><span>Ayúdanos a mejorar</span><span>›</span></button><button class="menu-row" data-safe-route="safe-privacy"><span>Privacidad</span><span>›</span></button><button class="menu-row" data-safe-route="safe-terms"><span>Términos y condiciones</span><span>›</span></button>`;root.appendChild(box)}
  function renderCustom(){const r=route();if(!customViews[r])return false;const root=screen();if(!root)return false;root.innerHTML=customViews[r]();back()?.classList.remove('is-hidden');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.route==='more'));window.scrollTo(0,0);return true}
  function enhance(){try{ensureBell();if(renderCustom())return;const root=screen();if(!root)return;if(route()==='home'&&!root.querySelector('#safeHomeExtra'))root.insertAdjacentHTML('beforeend',homeExtra());if(route()==='more')injectMore();if(route()==='profile')injectProfile()}catch(err){console.error('Liga Juventino safe enhancement error',err)}}
  function openWeek(){const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="video-modal"><button class="modal-close">×</button><span class="eyebrow">EQUIPO DE LA SEMANA</span><h2>XI Jornada 5</h2><div class="safe-lineup"><b>POR</b><span>Jorge Medina</span><b>DEF</b><span>Luis Gómez · Iván Sánchez · Óscar León</span><b>MED</b><span>Edgar Ruiz · Miguel Torres · Sergio Luna</span><b>DEL</b><span>Juan Pérez · Carlos Ramírez · Ángel Cruz</span></div><button class="btn outline full" data-safe-close>Cerrar</button></div>`;document.body.appendChild(modal);modal.querySelector('.modal-close').onclick=()=>modal.remove();modal.querySelector('[data-safe-close]').onclick=()=>modal.remove()}
  document.addEventListener('click',e=>{const sr=e.target.closest('[data-safe-route]');if(sr){e.preventDefault();location.hash='#/'+sr.dataset.safeRoute;setTimeout(enhance,0);return}const base=e.target.closest('[data-route]');if(base)setTimeout(enhance,0);const act=e.target.closest('[data-safe-action]');if(act?.dataset.safeAction==='week-team'){e.preventDefault();openWeek()}const f=e.target.closest('[data-safe-filter]');if(f){state.performanceFilter=f.dataset.safeFilter;save();renderCustom()}const dt=e.target.closest('[data-safe-data-tab]');if(dt){state.dataTab=dt.dataset.safeDataTab;save();renderCustom()}const inbox=e.target.closest('[data-safe-inbox]');if(inbox){const n=state.inbox.find(x=>x.id===inbox.dataset.safeInbox);if(n){n.read=true;save();ensureBell();location.hash='#/'+n.go}}},true);
  document.addEventListener('change',e=>{if(e.target.matches('[data-safe-notif]')){state.notif[e.target.dataset.safeNotif]=e.target.checked;save()}},true);
  window.addEventListener('hashchange',()=>setTimeout(enhance,0));
  // Limited startup retries handle module timing without observing DOM mutations forever.
  let tries=0;const timer=setInterval(()=>{tries++;enhance();if(screen()?.children.length||tries>=12)clearInterval(timer)},100);
  setTimeout(enhance,0);
})();