(()=>{
 const esc=s=>window.LJR_CMS?.esc(s)||String(s||''),route=()=>location.hash.replace(/^#\/?/,'').split('?')[0]||'home';
 const userIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="3.6"/><path d="M4.5 21v-2a7.5 7.5 0 0 1 15 0v2"/></svg>';
 const backIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 12H4m7-7-7 7 7 7"/></svg>';
 let timer=0,editing=false;
 const account=()=>window.LJR_V569_AUTH?.currentAccount?.()||window.LJR_MAIN_ROUTE?.state?.user||null;
 function avatarHTML(){const a=account();if(!a)return userIcon;const photo=a.avatar||a.photoURL||a.picture;return photo?'<img class="ljr-profile-image" src="'+esc(photo)+'" alt="Perfil">':'<span class="ljr-profile-initial">'+esc(a.avatarPreset||a.name?.slice(0,1).toUpperCase()||'J')+'</span>'}
 function profile(){
  document.querySelectorAll('.profile-button,.ljr-profile-control').forEach(b=>{const html=avatarHTML();if(b.innerHTML!==html)b.innerHTML=html});
  const heads=document.querySelectorAll('.ljr-scroll-header');for(const h of heads){
   if(!h.querySelector('button[aria-label*="Volver"],.v35-back,.v41-back,.v27-back,.v46-back,.v26-moments-sticky-back,.ljr-back-control')){
    const b=document.createElement('button');b.className='ljr-back-control';b.innerHTML=backIcon;b.setAttribute('aria-label','Regresar');b.onclick=()=>window.LJR_NAVIGATION.back();h.prepend(b);
   }
   if(!h.querySelector('.profile-button,.ljr-profile-control')){const b=document.createElement('button');b.className='ljr-profile-control';b.innerHTML=avatarHTML();b.setAttribute('aria-label','Mi perfil');b.onclick=()=>window.LJR_MAIN_ROUTE.go('profile');h.append(b)}
  }
  const root=document.querySelector('#screen');if(route()==='profile'&&account()&&!root.querySelector('[data-profile-customize]')){
   const b=document.createElement('button');b.className='btn outline';b.dataset.profileCustomize='';b.textContent='Mi avatar y mi camiseta';b.onclick=customProfile;root.querySelector('.v46-account-page,.profile-card')?.append(b)||root.append(b);
  }
 }
 function customProfile(){const a=account();if(!a)return;const m=window.LJR_MEDIA.modal('Mi avatar y mi camiseta','<form class="cms-form"><label>Foto de perfil<input type="file" data-avatar accept="image/jpeg,image/png,image/webp"></label><div class="cms-avatar-presets">'+['🐶','🐱','🦊','🐺','🦁','🐼','⚽','Inicial'].map(v=>'<button type="button" data-avatar-preset="'+v+'">'+v+'</button>').join('')+'</div><label>Nombre en la espalda<input name="shirtName" maxlength="18" value="'+esc(a.shirtName||a.name?.split(' ')[0]||'')+'"></label><label>Número<input name="shirtNumber" type="number" min="0" max="99" value="'+esc(a.shirtNumber||'10')+'"></label><div class="cms-profile-shirt"><img src="./assets/fantasy-jersey-clean-v774.webp" alt="Vista de camiseta personalizada"><b data-shirt-name></b><strong data-shirt-number></strong></div><button type="submit">Guardar perfil</button></form>');let preset=a.avatarPreset||'',photo=a.avatar||'';const f=m.querySelector('form');function preview(){m.querySelector('[data-shirt-name]').textContent=f.shirtName.value.toUpperCase();m.querySelector('[data-shirt-number]').textContent=f.shirtNumber.value}f.oninput=preview;preview();m.querySelectorAll('[data-avatar-preset]').forEach(b=>b.onclick=()=>{preset=b.dataset.avatarPreset==='Inicial'?'':b.dataset.avatarPreset;photo='';m.querySelector('[data-status]').textContent='Avatar seleccionado: '+(preset||'Inicial')});m.querySelector('[data-avatar]').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024){m.querySelector('[data-status]').textContent='Usa una foto de hasta 2 MB.';return}photo=await new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(file)});preset='';m.querySelector('[data-status]').textContent='Foto seleccionada.'};f.onsubmit=e=>{e.preventDefault();const update={...a,avatar:photo,avatarPreset:preset,shirtName:f.shirtName.value,shirtNumber:f.shirtNumber.value};try{const auth=JSON.parse(localStorage.getItem('ljr-auth-v569')||'{}');const i=auth.accounts?.findIndex(x=>x.id===a.id);if(i>=0){auth.accounts[i]=update;localStorage.setItem('ljr-auth-v569',JSON.stringify(auth))}const st=JSON.parse(localStorage.getItem('lj-store-v3')||'{}');st.user={...(st.user||{}),...update};localStorage.setItem('lj-store-v3',JSON.stringify(st));if(window.LJR_MAIN_ROUTE)window.LJR_MAIN_ROUTE.state.user=st.user;profile();m.querySelector('[data-status]').textContent='Perfil guardado en este dispositivo.'}catch{m.querySelector('[data-status]').textContent='No hay espacio suficiente para guardar la foto. Elige una más pequeña.'}}}
 function filters(){if(route()!=='leagueTools')return;const root=document.querySelector('#screen');if(root.querySelector('.ljr-function-filters'))return;const anchor=[...root.querySelectorAll('h1')].find(h=>h.textContent.includes('ordenado por función'));if(!anchor)return;const n=document.createElement('div');n.className='ljr-function-filters';n.innerHTML=['Todo','Competición','Jornada','Documentos','Administración'].map((v,i)=>'<button data-function="'+v+'" aria-pressed="'+(!i)+'">'+v+'</button>').join('');anchor.parentElement.append(n);n.querySelectorAll('button').forEach(b=>b.onclick=()=>{n.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const wanted=b.dataset.function||b.textContent;const groups={Competición:/competici|clasific|gole|bracket|pronóst|cuadro|estadíst/,Jornada:/jornada|agenda|campo|clima|suspens|aviso/,Documentos:/cédula|credencial|permiso|reglamento|document|pdf/,Administración:/registro|administr|control|equipo|jugador|publicaci/};root.querySelectorAll('.v734-tool-card,.v726-tool-card,.v60-tool-card').forEach(c=>c.hidden=wanted!=='Todo'&&!groups[wanted].test(c.textContent.toLowerCase()))})}
 function wrapContentMedia(){
 const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
 for(const api of [window.LJR_TEAM_LOGOS,window.LJR_SEASON_LOGOS]){if(api?.get&&!api.__v776){const original=api.get.bind(api);api.get=function(name,...args){const rec=window.LJR_CMS?.records.find(x=>x.published&&x.kind==='team'&&norm(x.payload.name)===norm(name));return rec?.payload.logo||original(name,...args)};api.__v776=true}}
 const players=window.LJR_PLAYER_MEDIA;if(players?.photo&&!players.__v776){const original=players.photo.bind(players);players.photo=function(name,team,...args){const rec=window.LJR_CMS?.records.find(x=>x.published&&x.kind==='player'&&norm(x.payload.name)===norm(name)&&(!team||norm(x.payload.team)===norm(team)));return rec?.payload.photo||original(name,team,...args)};players.__v776=true}
 }
 function bracketImages(){if(route()!=='bracketBuilder')return;document.querySelectorAll('.v651-logo img,.v651-catlogo img').forEach(i=>{if(i.dataset.v776Fallback)return;i.dataset.v776Fallback='1';i.addEventListener('error',()=>{i.src='./assets/reference/predictor-v36/liga-crest-white.webp'},{once:true});if(i.complete&&!i.naturalWidth)i.src='./assets/reference/predictor-v36/liga-crest-white.webp'})}
 function portraits(){if(route()!=='club-store')return;for(const b of document.querySelectorAll('[data-v431-player]')){const name=b.dataset.v431Player,published=window.LJR_CMS?.records.find(x=>x.published&&x.kind==='player'&&x.payload.name===name),src=published?.payload.photo||window.LJR_PLAYER_MEDIA?.photo(name);if(!src)continue;const span=b.querySelector('span');if(span&&!span.querySelector('img'))span.innerHTML='<img src="'+esc(src)+'" alt="'+esc(name)+'" loading="lazy">'}}
 const logo=name=>window.LJR_TEAM_LOGOS?.get?.(name)||window.LJR_OFFICIAL_API?.getLogo?.(name)||'';
 function iconSelectors(){
  for(const select of document.querySelectorAll('#screen select')){
   if(select.dataset.v776Picker||select.multiple||select.closest('.liga-media-modal'))continue;
   const options=[...select.options],label=select.closest('label')?.textContent||select.name||select.id;
   if(!/equipo|jugador|local|visitante/i.test(label))continue;
   if(options.length<2)continue;select.dataset.v776Picker='1';
   const wrapper=document.createElement('div');wrapper.className='ljr-icon-picker';select.parentNode.insertBefore(wrapper,select);wrapper.append(select);select.classList.add('ljr-native-select');select.tabIndex=-1;
   const button=document.createElement('button');button.type='button';button.className='ljr-picker-open';button.setAttribute('aria-haspopup','dialog');wrapper.append(button);
   const update=()=>{const o=select.selectedOptions[0];if(!o)return;const img=logo(o.textContent)||window.LJR_PLAYER_MEDIA?.photo(o.textContent);button.innerHTML=(img?'<img src="'+esc(img)+'" alt="">':'<span class="ljr-picker-fallback">'+(/jugador/i.test(label)?userIcon:'⚽')+'</span>')+'<span>'+esc(o.textContent)+'</span><span aria-hidden="true">⌄</span>';button.disabled=select.disabled};select.addEventListener('change',update);update();
   button.onclick=()=>{const m=window.LJR_MEDIA.modal('Seleccionar '+(/jugador/i.test(label)?'jugador':'equipo'),'<label>Buscar<input data-search type="search" placeholder="Escribe el nombre"></label><div class="ljr-picker-options" role="listbox"></div>');const list=m.querySelector('[role=listbox]'),input=m.querySelector('[data-search]');let index=0;
    function draw(){const term=input.value.toLocaleLowerCase();list.innerHTML=options.map((o,i)=>({o,i})).filter(({o})=>!o.disabled&&o.textContent.toLocaleLowerCase().includes(term)).map(({o,i})=>{const img=logo(o.textContent)||window.LJR_PLAYER_MEDIA?.photo(o.textContent);return '<button role="option" aria-selected="'+o.selected+'" data-index="'+i+'">'+(img?'<img src="'+esc(img)+'" alt="">':'<span>⚽</span>')+'<span>'+esc(o.textContent)+'</span></button>'}).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>{select.selectedIndex=Number(b.dataset.index);select.dispatchEvent(new Event('change',{bubbles:true}));m.querySelector('[data-close]').click();button.focus()})}input.oninput=draw;input.onkeydown=e=>{const buttons=[...list.querySelectorAll('button')];if(e.key==='ArrowDown'&&buttons.length){e.preventDefault();buttons[0].focus()}};list.onkeydown=e=>{const buttons=[...list.querySelectorAll('button')],i=buttons.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();buttons[(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus()}};draw();input.focus();
   };
  }
 }
 function patch(){if(editing)return;editing=true;try{wrapContentMedia();profile();filters();bracketImages();portraits();iconSelectors();document.querySelectorAll('.v734-tool-detail-panel[hidden]').forEach(n=>n.style.removeProperty('display'))}finally{editing=false}}
 function schedule(){clearTimeout(timer);timer=setTimeout(patch,100)}
 document.addEventListener('click',async e=>{
  const story=e.target.closest('.story:not([data-route]),.v20-story');if(story){const items=window.LJR_MEDIA?.items||[],name=story.querySelector('small')?.textContent||story.getAttribute('aria-label')||'',normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');const item=items.find(x=>x.kind==='story'&&x.expires>Date.now()&&normalize(x.subject||x.title)===normalize(name));if(!item){e.preventDefault();e.stopImmediatePropagation();if(window.LJR_MEDIA?.admin)window.LJR_MEDIA.edit(name,'home',undefined,{kind:'story'});else window.LJR_MEDIA?.modal('Historias de la Liga','<p>Este equipo todavía no tiene una historia publicada. Las historias estarán disponibles durante 24 horas.</p>')}}
 },true);
 window.addEventListener('click',async e=>{
  const feedback=e.target.closest('[data-v5-action="send-feedback"]');if(feedback){e.preventDefault();e.stopImmediatePropagation();const value=document.querySelector('#v5FeedbackText')?.value.trim();if(!value)return;feedback.disabled=true;try{await window.LJR_MEDIA.api('feedback',{method:'POST',body:{message:value,name:account()?.name||'Visitante'}});window.LJR_MEDIA.modal('Comentario enviado','<p>El administrador puede revisar tu mensaje en el buzón de ayuda.</p>');document.querySelector('#v5FeedbackText').value=''}catch(err){window.LJR_MEDIA.modal('No se pudo enviar','<p>'+esc(err.message)+'</p>')}finally{feedback.disabled=false}}
  const filter=e.target.closest('[data-news-filter]');if(filter){const value=filter.dataset.newsFilter;document.querySelectorAll('[data-cms-record]').forEach(n=>{const x=window.LJR_CMS?.records.find(r=>r.id===n.dataset.cmsRecord);n.hidden=value!=='Todas'&&x?.payload.scope!==value})}
 },true);
 addEventListener('liga:admin',schedule);addEventListener('liga:content',schedule);addEventListener('hashchange',schedule);addEventListener('storage',schedule);
 const root=document.querySelector('#screen');if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true});schedule();
})();
